// Code generated by counterfeiter. DO NOT EDIT.
package appfakes

import (
	"sync"

	"code.cloudfoundry.org/loggregator-agent-release/src/cmd/otel-collector-manager/app"
)

type FakeChangeGetter struct {
	ChangedStub        func() bool
	changedMutex       sync.RWMutex
	changedArgsForCall []struct {
	}
	changedReturns struct {
		result1 bool
	}
	changedReturnsOnCall map[int]struct {
		result1 bool
	}
	GetStub        func() (app.ExporterConfig, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
	}
	getReturns struct {
		result1 app.ExporterConfig
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 app.ExporterConfig
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChangeGetter) Changed() bool {
	fake.changedMutex.Lock()
	ret, specificReturn := fake.changedReturnsOnCall[len(fake.changedArgsForCall)]
	fake.changedArgsForCall = append(fake.changedArgsForCall, struct {
	}{})
	stub := fake.ChangedStub
	fakeReturns := fake.changedReturns
	fake.recordInvocation("Changed", []interface{}{})
	fake.changedMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeChangeGetter) ChangedCallCount() int {
	fake.changedMutex.RLock()
	defer fake.changedMutex.RUnlock()
	return len(fake.changedArgsForCall)
}

func (fake *FakeChangeGetter) ChangedCalls(stub func() bool) {
	fake.changedMutex.Lock()
	defer fake.changedMutex.Unlock()
	fake.ChangedStub = stub
}

func (fake *FakeChangeGetter) ChangedReturns(result1 bool) {
	fake.changedMutex.Lock()
	defer fake.changedMutex.Unlock()
	fake.ChangedStub = nil
	fake.changedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeChangeGetter) ChangedReturnsOnCall(i int, result1 bool) {
	fake.changedMutex.Lock()
	defer fake.changedMutex.Unlock()
	fake.ChangedStub = nil
	if fake.changedReturnsOnCall == nil {
		fake.changedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.changedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeChangeGetter) Get() (app.ExporterConfig, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
	}{})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChangeGetter) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeChangeGetter) GetCalls(stub func() (app.ExporterConfig, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeChangeGetter) GetReturns(result1 app.ExporterConfig, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 app.ExporterConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeChangeGetter) GetReturnsOnCall(i int, result1 app.ExporterConfig, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 app.ExporterConfig
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 app.ExporterConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeChangeGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.changedMutex.RLock()
	defer fake.changedMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChangeGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ app.ChangeGetter = new(FakeChangeGetter)
