version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Go Modules
  - package-ecosystem: "gomod"
    directory: "/src"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/src"
    target-branch: "v7.x"
    schedule:
      interval: "weekly"
    labels:
    - "v7.x"
    - "go"
    - "dependencies"
