// Code generated by go-bindata.
// sources:
// test-certs/binding-cache-ca.crl
// test-certs/binding-cache-ca.crt
// test-certs/binding-cache-ca.key
// test-certs/capi-ca.crl
// test-certs/capi-ca.crt
// test-certs/capi-ca.key
// test-certs/doppler.crt
// test-certs/doppler.csr
// test-certs/doppler.key
// test-certs/forwarder.crt
// test-certs/forwarder.csr
// test-certs/forwarder.key
// test-certs/loggregator-ca.crl
// test-certs/loggregator-ca.crt
// test-certs/loggregator-ca.key
// test-certs/metrics-scraper.crt
// test-certs/metrics-scraper.csr
// test-certs/metrics-scraper.key
// test-certs/metron.crt
// test-certs/metron.csr
// test-certs/metron.key
// test-certs/prom-scraper.crt
// test-certs/prom-scraper.csr
// test-certs/prom-scraper.key
// test-certs/router.crt
// test-certs/router.csr
// test-certs/router.key
// test-certs/syslog-agent.crt
// test-certs/syslog-agent.csr
// test-certs/syslog-agent.key
// test-certs/system-metrics-agent-ca.crl
// test-certs/system-metrics-agent-ca.crt
// test-certs/system-metrics-agent-ca.key
// DO NOT EDIT!

package testhelper

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _bindingCacheCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICiDByAgEBMA0GCSqGSIb3DQEBCwUAMBkxFzAVBgNVBAMTDmJpbmRpbmdDYWNo
ZUNBFw0xOTA0MjIyMjMzNTFaFw00NDA0MjIyMjMzNDlaMACgIzAhMB8GA1UdIwQY
MBaAFO8+YYjqHJbIkBGrNRutV3CV5YfTMA0GCSqGSIb3DQEBCwUAA4ICAQA/KP9b
vE9QutkAmXnfWQuw/Bqge5y+Ug06Zfd0ygQgpZje61VI8BEDBr1ybXF5k+3c0Eah
5cl6tK1idrYeKCL7mza28vb91D8xjodZdpm1ABz8SSK4orfbxo7WW2o8ryZjnGCX
BTQUVjEzSILEI/FvwDkuEeMTmMPgVdMYLJSQ3Kx0PNQ4YsJNUvEZ/piH4DMQ7NQD
B1vH0+1sYMN+0CJqc04l+f3k2hALpc16I1fFJatLH7EE4OVizu1JBwJ4AvzeFrwc
GMem52LTeF1A5AWW/IK/HnDL3xUQiJm40cDORwltXu6jO7XnCTMfstyQM1eD5Bkz
M4sXhaaCbL1trf5Ow9mr3NJHppF2zYlnfB+y0ggX+jvqK1FmeiDzbpSeeSjbXQw+
+hf/k+nzjOFhIS+H8jFsWdczTL6Qqu4SDMuKDcP1kLQXyA5tDZjg2o0h1YDkaLuR
PLy5Oum+b5Dugcocjpj4tWe2zss/KRmEknuV3B5mUTdRP64o0x4M9jhssNgeKxWW
CvaoNLNnIY2hD+rXIDLH9snUAUZsGhPIb04WbjTVhmiZCEsHkNCsnQXqnbU4H8Lp
WljQnpMNFbh9LFE2oozlpLHRB2FV49kRDQK8BFRNSNphmLxRz8pILF4tGwnx7ltL
CEj/4OuP+k5O1cyMuLR6drVN6J5Coj//MlZwWg==
-----END X509 CRL-----
`)

func bindingCacheCaCrlBytes() ([]byte, error) {
	return _bindingCacheCaCrl, nil
}

func bindingCacheCaCrl() (*asset, error) {
	bytes, err := bindingCacheCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "binding-cache-ca.crl", size: 934, mode: os.FileMode(292), modTime: time.Unix(1555972431, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindingCacheCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE8jCCAtqgAwIBAgIBATANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDEw5iaW5k
aW5nQ2FjaGVDQTAeFw0xOTA0MjIyMjMzNDlaFw00NDA0MjIyMjMzNDlaMBkxFzAV
BgNVBAMTDmJpbmRpbmdDYWNoZUNBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEA0Dpu9GsxZBhI5IRcO++kTAYpJa8bLuNtduvVGU4B/zXrFIwJUFpmKSzk
74xdj/+HEH4r+tM88ll044PoNLyLRzVNswAgmzhUVpIndELI2XzX44odVb4y/MLA
23Ggg19M2lcyo3TK/XsQusOm3jKqkugy7BzF4wUhodFfZB310t1HSw5PrTB9b8WN
g72O3q1GDTBF6bvK8+VF0VKLvx3GSO28W+QqqUNxdwMrifgDSaZXh9sI0LqVr3zp
Ljch5kuIccU7zmlrwjQoAVhyL7ocrjNe5RWnsvph8cBQMJMPEuBT5Py6gYvGlpA8
ZlobDIYr2NMA8S6fCjLfO9fiHEIsUO28YGtGKlW7V/ujzVvQ5wH/X8oz92v02fFT
gdNO8hO8T7RUenIAAMkQCv/QLMU9EbpqKwAkeMvQ7QDfDADzYGU2sgKBqLKTbS//
52GaLGT0yxwAgSaSADLBtyMer+X4rFgiP1Fipd844BUVPMx5rKImGcd2sLpjQ6yV
Ut5h3qSPbKmoHZAy7WFkd6aTA/d3JFz0F+u6OotgUm06qqsNA2jmFcHUSC1rkBwj
zFByB0+TkWTCjbgJGsHkuPqn/NwHE5aYdnGVkhCQSn3RRgQB40PwHvImGNYZasWK
Ktx9TYbgT/Gqw+H/EVyDHGE476Kc4XkwHOgsmV+/EG6tMZFLoaUCAwEAAaNFMEMw
DgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFO8+
YYjqHJbIkBGrNRutV3CV5YfTMA0GCSqGSIb3DQEBCwUAA4ICAQDM7jUN112SWSf9
7CRNy9+FpPOKTfWi2xVSuMV2U/+r0GzykaGrWYK184PROCmtEtr3sm3d/nkK1Yv0
NGqFy1Ehe158BdhfK47tPclwZ3/4UBDW6FBHykJu0BGKDv2fTnGnnaCt5d7LFBJm
i1K4/I5oxnUpq5tyF9PKBygZS+L1my9stqj5XpDr7+7eeoREmXw7Tv/n0+LTMiSo
TTSBfJ9KKdlzra0NF9y/UUHQu5KsevWq94YHw7kdfllSaunboH0Yqx0gcVCeyZhw
OqRpMk+/ydKkT8m24Y8Ue9YmPjeXJvnlAYZtiTLbFGXk0eJ7/um7cLVZ5unP1Xqz
pag24XrgF286u9SfOsfWSvWI9/ZYnJV7DGOPhY5GfamdlEAOcyGHfRp+wotFMqCc
UHXSXiUmOk4TZ2BKCQce9iqKJiDF8fO/YV2inIs9gPpclOiU9r1Z6/RWCqtd1kE+
We16haCUHAoiJCZmpJRUO3K0Zd/4F9EQAiVzqFc88F2lK6RzqMl39BEe88vLx8j/
laVktDnnG3ed+i+fmlpGAVWdGZ6dwrVTsxWvMjjwhCntHQt3auuKeabUdF051zKk
61CNRDshtnnaPLKhMerc9UFWJaJEWfKlFtUr8bferlTghWoRj0amoeH0ZrzZJpAU
cPAej40o2L+dOoR+AXdzoZZOj95Hig==
-----END CERTIFICATE-----
`)

func bindingCacheCaCrtBytes() ([]byte, error) {
	return _bindingCacheCaCrt, nil
}

func bindingCacheCaCrt() (*asset, error) {
	bytes, err := bindingCacheCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "binding-cache-ca.crt", size: 1777, mode: os.FileMode(292), modTime: time.Unix(1555972431, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _bindingCacheCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEA0Dpu9GsxZBhI5IRcO++kTAYpJa8bLuNtduvVGU4B/zXrFIwJ
UFpmKSzk74xdj/+HEH4r+tM88ll044PoNLyLRzVNswAgmzhUVpIndELI2XzX44od
Vb4y/MLA23Ggg19M2lcyo3TK/XsQusOm3jKqkugy7BzF4wUhodFfZB310t1HSw5P
rTB9b8WNg72O3q1GDTBF6bvK8+VF0VKLvx3GSO28W+QqqUNxdwMrifgDSaZXh9sI
0LqVr3zpLjch5kuIccU7zmlrwjQoAVhyL7ocrjNe5RWnsvph8cBQMJMPEuBT5Py6
gYvGlpA8ZlobDIYr2NMA8S6fCjLfO9fiHEIsUO28YGtGKlW7V/ujzVvQ5wH/X8oz
92v02fFTgdNO8hO8T7RUenIAAMkQCv/QLMU9EbpqKwAkeMvQ7QDfDADzYGU2sgKB
qLKTbS//52GaLGT0yxwAgSaSADLBtyMer+X4rFgiP1Fipd844BUVPMx5rKImGcd2
sLpjQ6yVUt5h3qSPbKmoHZAy7WFkd6aTA/d3JFz0F+u6OotgUm06qqsNA2jmFcHU
SC1rkBwjzFByB0+TkWTCjbgJGsHkuPqn/NwHE5aYdnGVkhCQSn3RRgQB40PwHvIm
GNYZasWKKtx9TYbgT/Gqw+H/EVyDHGE476Kc4XkwHOgsmV+/EG6tMZFLoaUCAwEA
AQKCAgEAyq8WMXPlr7izuzvbS7wIALg+dR/tJcbaVldYJjl4WCLzoBxvNHfJ2WqJ
rWLD79aaccNeq9fSC1RoIs3SyQJ9z+Jir0oAcxZxgZLiNJiNSKXsvt9BjqSEnOQ1
NWV1CGtLM3yNHe4haHrR3fl0A/Ttc/HxH0Mim8fy5MAYSiufjJE3RCe6Bqqcbp+t
D/8DglzHQy8p3kmdU6poO0hOHsmsqHBAWHHP1NKBL4c2aiWvjZEMwoDCI+p6qUa8
8u9XYANF3PhPLqwO6Ao8ppKhEzPllusKA5MAmYZ+sAKyC5YZphYVk18ta8vSkdvz
7uzmR1qSc4tv71OiGxtJj8ajoT4IQzuATGBL8NKx/hnMeh08kp6lqWvYD2at8QZq
pK++/5FdVBQkiqXd0IGlj+qs/TrjO5bW3Ar3AnWq+TO2az+O+mVTqZtdoQx4QGZ7
l+SetseAdQMWRtyt+Ig8pxEBzLOGa9VGOo7lo8+f5Tn1Ie8IE0ZWtPMh/fGOW3Wo
/b5DQ91xp+lyXLAejgxBy7fQOe3i59Fs8pZwpjkKMl961omCzu+DkH8aF+ii3kzq
ExWyJZzt1EMpTroW1u+zK+p5PR99VIqoUYapcvqoVFVtR7v1VMCQulW7sV2Xsag1
DZBzosDkifS7pcm9yrwakdpHqNuyJy5n8eJSRDcVYaJbzOfEYAECggEBAPgnEoj4
MdF8IIXZ546Top6Ul1rVjlASks9csGzspBUMbVL8kyatFqJ5pLhTY8vHM1fgWIQY
m3dBtF5jCoUm61+I6C3P6L2nGlBtKFyJs4IojU+Vy23NnjQQaLKW0Dn1SOXCxUMI
rjf67ed+n8P4Tpgd+z+1nrOHGBfnDxO5DCeTxXo7PKh2SPkLL4aFh13gngXVfplO
gSnqbnsKeh1Y5ZM6/DE4WHkeVRidGLiv8KVliOjBNy2JrIrGIntvD8eMccyQr0A2
Z500XMNGy1eDDee9omEhgLRYwUhnNaUbjcguUWzizfjzX277xTYj54e/Nbcs3/nL
YrKDboqofl+cIIECggEBANbQJugtq1feENLI2sh2Bzd3FCGKu9CT6ZAp4i5Qpmik
0Y06PnKmXEBwcigqgIP06WNtbi7rYqQPYuOoYM86mWlGOV1+diPzZjSJkiMWZdrv
cRZGlat03xzZkWsqdZPsJcJu0sWaKkr1kDhl5UBTpDnDTnRmRmgmqg5GKzwctdkq
HmBPo5NzMeFRi3EJPfCae5me3yra8mxf0i+EyuTMGMC57pk8G95xi3fWtJ7+JHks
voMT83QRDTvlAqJCdnOYJtyZay+YFIn6uII5M9CHPe6zDYYUCkHy8MLGqrZRTHjf
BnF++jDRDfagATzUbNW7sWfubuiVlOXDJFToUpwjbyUCggEBANh6nXzHqA4rzuN1
2L9Uo8Tbs74WFvRbf59OKMqdFfcWxDhlBqnyzZAntj7m4GRg/rVmjVGPdfBvbT36
AK9v6F2LPaDZgxwPrrECyPcRWXvujHglITZE7gJVXkCNuFEXXeSyKQv1gqZrTSdq
G04GS+oAHbLSagQLkkUn2MtH3waXruqWyq/boIVB8M/VpOWMkc5dFPgAuEUssfy8
gxMe/geWqXL2yJfAklPKmEplkfV3whvqkowzUkYt2t77YDSgnJXskjXeQD2v9EyW
ccWCGptTn1hEtdaept7WysGia+l6HqZypWTMSzCyirRUViLh96Y4i5uKhitc5Q4p
NzWJKgECggEBAIqr1uH9UWYouc2I0gukfeYlXf6FM9djFNz23McvUy2scIZt+hBD
KryCmn8paMtGmD+SThXF6Gimch0q/kvotU5Lgg7D63orz2fNA2TZOamK9wL9T/Ne
QAW8we5fe4WhZYLNzgy4B+NaAN8XkFXlaNfNJ+FmgL8NbqxGSfTFR/NICFH+N0eh
jqq43H59C9o9r9qsv75Hl0W02dfJLr1ir/wCS2/qaMdBn1oeZX1Z7Ku44cd2Yqwj
sdpfbULYCuV2bGfuNk6EK4YjL2cJjFRqaeWk+u76EuEd9qSWYW/OrcI9n0g3Q0Wu
PwhdpE7jhtq3DsBcIIbOwU9NmS+ixml7Sm0CggEAK14MZx3vA3ro2QmoW3PZ/fTh
r8KwS7VlLU94zFCHEQEqoEjbdMqqhtLZTGelXodJYmSCCAlDfKsmAVZe85E9Owgq
RNEsAvXNOJDIocbeUg5uNzrhETDzaQJmT52Oz23rKa0VPjmq0OIcSPmX9Z+RzJtM
oNNnPJl+Gawvtbb1Y1rgyBAFif0m+pRRwU3MZMh3cQfhWsh7tAIuzq9e5ygEVEqA
E9IDQbyXgCjClwvEAGdHII4JoPJmjeoeW5K8R6ZIT1D1/W3l2HQRbk+FojArQ49b
2VGUqBdIimSjBZG+92YnYmipgUVzaeIoWLRxAr9GXxwDBmEZ9lTikqUEKNHwQA==
-----END RSA PRIVATE KEY-----
`)

func bindingCacheCaKeyBytes() ([]byte, error) {
	return _bindingCacheCaKey, nil
}

func bindingCacheCaKey() (*asset, error) {
	bytes, err := bindingCacheCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "binding-cache-ca.key", size: 3247, mode: os.FileMode(288), modTime: time.Unix(1555972431, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICgDBqAgEBMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMTBmNhcGlDQRcNMTkw
NDIyMjIzMzQ4WhcNNDQwNDIyMjIzMzQ2WjAAoCMwITAfBgNVHSMEGDAWgBQ2fCM5
KKaRkeKYTIdhM8gTf/V2STANBgkqhkiG9w0BAQsFAAOCAgEAEpjRT+xRw2+YCATK
Ow+GZD+X8CKj/U3g2oOJEQLhGGLR6JLxE1Py13omkCKKfWPW/eqW9zFet9rgBYE8
UKpExj2XVJr4Rl2jWuDxnSH0dbKVkx8Enge7aYyBBWvB35RXWksF4t9Ql/ZeVBxC
TDd9ky10yFfSzjtK1zzf168qgLlX1g7RK0lnTwD4DC+Sj28j4UMuMQtl32BYTz92
Kl3O84lT1REN6NBkSmSaAXY4dG9glOq3pKy9qOEewpkBJEGlVE/K2+GH7O9QBnl0
WxnivDNBmr3xJcGPh5DLrmNZwcRqXC4hBPykmcD9+23Df+Wj6fB9BjeVl6fb9w74
2RsjZNwzKL5YYZLg+uYFqFjk5FWBAm3RfvvEbHS2iZVb56I7j982xDf36yVN3kon
N2zzKG0RbRzebiAFYzAYGpQlpprhh5eF968X4CJpOyKtALNJ5Hbg9cT2+u399vSh
YLu/2CKkISL1b5Vtq7z3ur4xtZxczCorlwnMxygyxTORzDkWWGy5boaPfSv2HD+T
mURDsKgxTv5adRpenVgA0u6w8eeIKNqDqatjEk8O3VF2K+nWdLspwJruSniAcr2H
TXV6+DpsTg4A+VyzQDOueT1OZLwTJFcK6jCw+gFsmg/IN57j7zyyivYRDQtZNaQ8
sGNnlVk/mYxP7mlcauW2lY8GBCY=
-----END X509 CRL-----
`)

func capiCaCrlBytes() ([]byte, error) {
	return _capiCaCrl, nil
}

func capiCaCrl() (*asset, error) {
	bytes, err := capiCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.crl", size: 922, mode: os.FileMode(292), modTime: time.Unix(1555972428, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE4jCCAsqgAwIBAgIBATANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDEwZjYXBp
Q0EwHhcNMTkwNDIyMjIzMzQ2WhcNNDQwNDIyMjIzMzQ2WjARMQ8wDQYDVQQDEwZj
YXBpQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDNmRBRkionaGGL
mGFeZkQCLd3RiDihJBBoApPyWs4KKULDYnpKCX4RjSj28WyuWSFnlTfG8775g9QK
N5Xnph4wbxKbbYiA1JM354BtN01K4MmCKnT95gGATL8qe3JvHqSzhxeiJdk213zy
iO+dVfCgLwZWIva8KHyo/R/khYJi4iQag5JxJItgqzGwHDRBPxpNeNqpEjRcVAdp
9A8MvzEwMmMEOLwcIa8huese6pk3Ckulp3LGjKdjIDCDsAbW/yeU5POJ2pRWW8KQ
JL8Ffs80JD0IHB5Jr0x5p+xmdeyzs1Tt0iG/ci4ZHjVT0CnfJCcxsv/X5pVLsoP7
F1G4cYkfwBj9j6HIDZvn0OaqN+kG6yM66ME2T0kg7okYF8+BOKP6xFH8am5Avx6E
BhkOgoud/fqbC712shQ8G8S3MohzWn/7fxgr2jeOyyrnPFCjYox9Rw/oVt3Imn/k
myDge/CEdfaI3jkpb9BOSjepwiC1udO3yFPTZ2d/T/kvLkFCrbij1ahIt0fT//kX
LOmkWCHzTIW0UhDYUO7oSTFCx0ZBClLKM2XFEmuRZVkYi5g4E1wZyLi/Q9aIA7fe
K6kS6pzCgP04ZEVb8i1pmHNQwy65KG89MH3YJ+v3GWzRhMzoyy+Au0+Vf6BBBzhL
1Xy8TNgvFCyHbEJ7X1qZW4p+9A2iXwIDAQABo0UwQzAOBgNVHQ8BAf8EBAMCAQYw
EgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUNnwjOSimkZHimEyHYTPIE3/1
dkkwDQYJKoZIhvcNAQELBQADggIBAEDIxdH0Pv4nCbHjEdjnmxGNErs+l6ORJztA
Huxs1TA6vKJ24Zf4ttniCblT1L+3sFPj2HDrS/FJMvXNjDEkUTFInrjqlZuuxCCm
zC8vET+ooRZSpUzXJEf69EL8SF5C+LlDZ6e3Eu86Bb22Wi5y2UX2fG8yUKAAhvl5
m1fRZLBFpane05El3L2uKQWhPw8S6UFcp648STcmdVg9ONC6An8GC1OtEThIGtMf
+WX81KqwG3sQuWyoLPoXvYCL9J7RySk7pF9gSmCrCL9ZVdR6PoKXNZpOKepTHf07
r0/FC940hNznesglTv0WpKJAtX/Hpoa9CB7JJt3fyR2uzEk7jMNSNykc6V0jrjrH
9Lj95Mo6IMTOddHV8OROE0wXaarbVZPoWJEcGdCeJLtWxMciBHHaUmAJo5EDl5U0
aztsF9bVoifkS8Sbpg4j5DBK4Mrur10jsS57Q+EX4VaYBBhuEb4kBPU20ZL4Z2yn
FN11aX6WlKfLtOjtqOAd7u1uIMCcwQ0BfgvPQxZn9a6IdZ6AXnBFCqvCfWbKEoUr
eqfXHp331Nem90ciqCTyv8e6rvZ8rgLo0dob5JYIy7Y/qh+vfF3YOLAun1RhOXPg
sigcP1H21Piwv4bGjtobEuT0DoC+EL8+QLqLJ0TUuUk3L11dRzZJcrBHKog9IRqM
62Z3RtDh
-----END CERTIFICATE-----
`)

func capiCaCrtBytes() ([]byte, error) {
	return _capiCaCrt, nil
}

func capiCaCrt() (*asset, error) {
	bytes, err := capiCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.crt", size: 1753, mode: os.FileMode(292), modTime: time.Unix(1555972428, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _capiCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAzZkQUZIqJ2hhi5hhXmZEAi3d0Yg4oSQQaAKT8lrOCilCw2J6
Sgl+EY0o9vFsrlkhZ5U3xvO++YPUCjeV56YeMG8Sm22IgNSTN+eAbTdNSuDJgip0
/eYBgEy/Kntybx6ks4cXoiXZNtd88ojvnVXwoC8GViL2vCh8qP0f5IWCYuIkGoOS
cSSLYKsxsBw0QT8aTXjaqRI0XFQHafQPDL8xMDJjBDi8HCGvIbnrHuqZNwpLpady
xoynYyAwg7AG1v8nlOTzidqUVlvCkCS/BX7PNCQ9CBweSa9MeafsZnXss7NU7dIh
v3IuGR41U9Ap3yQnMbL/1+aVS7KD+xdRuHGJH8AY/Y+hyA2b59DmqjfpBusjOujB
Nk9JIO6JGBfPgTij+sRR/GpuQL8ehAYZDoKLnf36mwu9drIUPBvEtzKIc1p/+38Y
K9o3jssq5zxQo2KMfUcP6FbdyJp/5Jsg4HvwhHX2iN45KW/QTko3qcIgtbnTt8hT
02dnf0/5Ly5BQq24o9WoSLdH0//5FyzppFgh80yFtFIQ2FDu6EkxQsdGQQpSyjNl
xRJrkWVZGIuYOBNcGci4v0PWiAO33iupEuqcwoD9OGRFW/ItaZhzUMMuuShvPTB9
2Cfr9xls0YTM6MsvgLtPlX+gQQc4S9V8vEzYLxQsh2xCe19amVuKfvQNol8CAwEA
AQKCAgByVfLrShvDOps0pJNRihG8HIHFKrpDcujkzro0ByeaIwQL4FIdplXDsPrd
Cbnk45BeKG+SZq8H17Yt0Ge/IXScfsicQzesXYtZhZa4Jg8H2yZ1CuNw515iWUve
djRXc3UombIc7Gt1wjSsNFb86nQcwMoHUP5h+SoKWGpKDa1LDHQDgrQH08jnA41o
YOb2ef9IojMH3yXbSqes1psf/Zt/MCY8jMif5GOen+QPl2uJXmJfR1Xe8Q2NZLNW
KKhFHDSI6yI8wZ/IvtLeknDgv3q/hn+iaPC3DZO7/BTNjjsKXGqYr0kxTHAya8hA
Sf1fKJ3bV65MBOF17VrUYk2CAzG7xA1qWjSLTUJOsfCIEBNoR4Wxlae3cb405MOz
UA64yyqFaquct1FrZut2lnG6zE3rNbNwJtZjvBval07kyiUB9MwLvlBI2HkeUIkR
1noRYG+BkF6/pCjstSo0G6Edkjl0zJ/WPHpZJY1E1WeWR8CfusMDtG99fOnVUwmN
TopPSC7yx5RUS0fIYkVgBN4FrPe5UW6rU2wJr5AyFPbF80+EkV2ku8Sw7Pb8sdWB
CxiN5ya0i+8chyW2SeBGrKHnKSDeL1ToYoVxStnuryj48dHA3Shy0JZHX8E7DfHG
NoYD7sek60yUsAaIduejP5EVhYdX4+AethTV/OYtPEV4f0V2sQKCAQEA/VjnlnCa
7jHUmiZeQ9tZ+Q5k5V73Rh9SUHETDRl4S6H9JBkUBfcMRW42W/P2X+COKmlgKWXs
88Wh1iZ5liRhMBB8sojD6/YQLZMO7A1Nj7Fx0Ty99aWxYLh/0PXXlKpMa06uq/wK
ff6oFJlIs3KZaDNO3hYQTZl9QccgnGvfHeEBhMY2yw02x8pjIz6VDxXEhYHJYipB
gz6t14+iqfUuxDjLtOjYi1vvtPu3tgtDyqcBQpxbYbQgucTkb+2UNMGToIXgJ44M
pgRWQQRGFgwBsBmlz+MIdUdQwFBOKwyt3z05qaZDPlZ9e4HXIcGCCdxBiwwtkbpx
0GCVyu68Gg+A4wKCAQEAz8Aq0tWSUCoOzQ7ePy/S/uElG+qz2aeh1tSLtZthJjBN
sS9t+FX52ZNTUAmiqg8+KPYuaE01aJ2z+NIB7Uu5iYN7aTJ7sO+PYKR1Jo39AezG
CPab6SjM2p/Ib0SNSLgkeNEpd8mFYnfoIgEj2qOpk99icVH2xGWEF+WMUHS9Gf2S
SIRB1G5JJAZlohc2fKMAgjUYVxbPBu+A+L2hj5acWOHpv8KHHb4R+/wWpDryr0E+
GSfWEKygou0kQ8yNCEM6kEHoSo4CaOT5Jeb7/YrhD3D/39+iNab54mX/fgWOAtV3
h1GFMIGLtUtr9KVKbUNWv3qM3HWMqHHfP0dP53N9VQKCAQBqor4vu0vrEHxdOeMZ
ir1vMFjVlshb8pkSFNYhAGR66T8Er62W6Sp4GvC0eZZtOrZ8MYhxRF6dKMV6vw0U
XlGuCnKCL0DQE+0xUaHJR7wqzFSM7pVCTTDA9keOa7wG7jtmO2MYLuk3qTWUHgTU
y1q42kfLANxx3TY0tp0KWfk6uVeLTGcJxpEVPSHHVvMku1PRohRixkh29q3zepjM
EtBRdVqA1jU3S0Y1FnJ4JHuvU+Ya5HcuQ8Q2jSJd3lEwd34s5cy4uXindFHd4e+i
HgGj3tfFDdmki5T4rZSJWDfjLAEWYE4TchI1JyynH60de2D3JvQTT7fSLqU+GoiA
K6BjAoIBAQDCoIA99pFVAqHNH7G8NnyQBbLzPWTycqYekg60u3U/Bp+ycAGxVjJ0
0B2L7Qr0EMWmMEP3uOVhNeUGJRBjE78lAgWa3w2cDEIhQtDxprGxnPVGLmqP+4Y3
BtwKyYkm6ERa33De5O9N+ZGCUdkaGptiijM6gJQTGBuxG37hXQxPjgv+XdEiR5PD
6S5LtT15dGeklENSS272S2hjH5x83ZdpeXO4D3Dvv0Iv9NHtV8BFyXR4sqZMBr2T
BWElFzvE0t7JiMUrG3FMfb6f8I6A0BvakH1WabcYVm7h17aMhH2vT/bj0c5aS/Lr
jFX94uAgDqb1ScUvP/zfTZbdPFyyM7LlAoIBACjF9bdbYZ21yCWWvX1KMjuFvpMV
iA4FsHUaPY9UKqeXpalhyFDC1AjDbQDnsLkfondDcFM1CyL2je7DXL7/QHwUZhlm
0if2+LtClQoBgTu+n0Kkp7CUKNVfSukfL+fXIc5Cj+6RSO0jJ58eUsCFIZGwXVoB
BUlEKhLNSYiLGf/6Qs0HsVc07QbZ94KTJ/Xf3BxKuWXrJIoklyFjyh2yxgBdG/mf
S5hSbNmR5nFaow6qfxfjcJ0vjynuTSdUsIVdhCYKUY/2y7NikPhDbcxJAdTY5eL6
V5fQvmUNn27SFmGjYjKGkm3WV45ObV/AitjrvIYqNr8sIzvzRBivK5qgCkU=
-----END RSA PRIVATE KEY-----
`)

func capiCaKeyBytes() ([]byte, error) {
	return _capiCaKey, nil
}

func capiCaKey() (*asset, error) {
	bytes, err := capiCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "capi-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1555972428, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJjCCAg6gAwIBAgIRANXrp1KGu3OnEK1mUCTR1TowDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xOTA0MjIyMjMzNDZaFw00NDA0
MjIyMjMzNDNaMBIxEDAOBgNVBAMTB2RvcHBsZXIwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC2ZwZ6rj58tNmAC1p8m8uHTijrBhTMux8/gz9+KP+5XKFh
SOVKGJQlBM5ksyGfs9KZTMbjF4K1zXU7jOeORdeDzRQpS3WDWwk2doYfL6DehfQe
YwhkmJX5Yoz+LaKIZwk8TfNGW8q8a1h4vvhuwZYFxeiDm2ORwr4JV8bvv+4wqwJa
CaNdyLZWy1rDTb893kra6bUy8lk1XY6ZfH3ZJmiGA8SXBF2QF+LMtJc2q4QuO1YY
9hsZSrAqyYbecyKE1i1lQmZV9tfUXH4FzeMTQkiXwkp+m0Kna6K8V6fy0xu0cOvH
rNZWldjA8oNg/9UAlDQ4Lzwg7hFillLW1PKw7C4ZAgMBAAGjcTBvMA4GA1UdDwEB
/wQEAwIDuDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYE
FGsYX5mnmwlKLsftqla4RapXH0vEMB8GA1UdIwQYMBaAFHraADLgKR0US44KFxqT
9WMIU96vMA0GCSqGSIb3DQEBCwUAA4ICAQCic5jZ6l6BFfBXOePVgMgTKy8JkPIM
xQ4qf2wEB9Xgo893xggotWrzn1o8c/a/Td28m7AKgynKmMJXo4TMSYp6eXy7bVNJ
5IefDwifhCBP0JmkWekK0xpLzU0x/SeLbiVSkEt2YRzMTe/R1qHZO4m9ghq74S91
YsQs2blITdMT8SMudaqMBY4utScc0eYROn+tzJG4SDPRSSaXPDOWcboqyz5IDHEc
p2iOdNoOXCaJz3Slq+19OoBUOi+FcK4cq9YziLamgbnFe8TcUuLYyoiqYfIi+EFg
bi7uwqQz/7+6V/V1XtfFKSOSyoKbRlgidxZ6arKRQ/zhF2uL0nAXCXAm3zueWBA4
pcbo/+LLuoAeYfuTlIIksxqjNK5oPJL9Kwek8PZtRriuHq+MstsY7F5xRSTIbVIo
3AZO6U35JmoExfdo6TUk1VWf33ZYABB8zUU/f3cfLVITEWghv/lCl/j5hMxLWCcK
VjOgZ+D6pkj0d57BqsaEz4dTBgKP3yxASOKospCapOZk7druYLMQaRUx77pBtJTY
7pQnLJHE7Xl1YzOUzODxmRil6tgU08EyvsJsfpMnnW6UCPSh45Ximp/3MuilCL9y
iy0w2UDJMYBqLakJxG0MkAsEmV1BQ8SdT6UM03QYTOAeDkcXBucWpmh48HphIS9v
h5v6TsNK9e4MJA==
-----END CERTIFICATE-----
`)

func dopplerCrtBytes() ([]byte, error) {
	return _dopplerCrt, nil
}

func dopplerCrt() (*asset, error) {
	bytes, err := dopplerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.crt", size: 1501, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVzCCAT8CAQAwEjEQMA4GA1UEAxMHZG9wcGxlcjCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBALZnBnquPny02YALWnyby4dOKOsGFMy7Hz+DP34o/7lc
oWFI5UoYlCUEzmSzIZ+z0plMxuMXgrXNdTuM545F14PNFClLdYNbCTZ2hh8voN6F
9B5jCGSYlflijP4toohnCTxN80ZbyrxrWHi++G7BlgXF6IObY5HCvglXxu+/7jCr
AloJo13ItlbLWsNNvz3eStrptTLyWTVdjpl8fdkmaIYDxJcEXZAX4sy0lzarhC47
Vhj2GxlKsCrJht5zIoTWLWVCZlX219RcfgXN4xNCSJfCSn6bQqdrorxXp/LTG7Rw
68es1laV2MDyg2D/1QCUNDgvPCDuEWKWUtbU8rDsLhkCAwEAAaAAMA0GCSqGSIb3
DQEBCwUAA4IBAQCObZrmsYpPwAqH29F5HXPgdLiOk4BKlM2Dl1+DTCg/SOFi/swu
hn3Wtk1Limx/68YIg4Cs6uG25et4B3zpFZBNVvXwtZjHxmgo2D8OGMy3Ms4YRL4j
m3AxlfRGazj4ehYqV9N+Gz2d3o1i3lmPlk3NKYRJYh3fw8jg8cwmovRRbhCwiTFi
CVbXCk2pAY1zaCceqi6apE8SwuJG423JgwiVIx4KYsDtOFVXN7vkfZe7QIjhVjB7
/Ol8L7sihShG3jWcFUq5GP48uMZvwqHwgvXtGkkDAE3XpbkyUrCksx7MbCz+IMrW
6KfgreM9GrhipdsXu8mNFpqRPbKkVYJPeq5T
-----END CERTIFICATE REQUEST-----
`)

func dopplerCsrBytes() ([]byte, error) {
	return _dopplerCsr, nil
}

func dopplerCsr() (*asset, error) {
	bytes, err := dopplerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _dopplerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAtmcGeq4+fLTZgAtafJvLh04o6wYUzLsfP4M/fij/uVyhYUjl
ShiUJQTOZLMhn7PSmUzG4xeCtc11O4znjkXXg80UKUt1g1sJNnaGHy+g3oX0HmMI
ZJiV+WKM/i2iiGcJPE3zRlvKvGtYeL74bsGWBcXog5tjkcK+CVfG77/uMKsCWgmj
Xci2Vstaw02/Pd5K2um1MvJZNV2OmXx92SZohgPElwRdkBfizLSXNquELjtWGPYb
GUqwKsmG3nMihNYtZUJmVfbX1Fx+Bc3jE0JIl8JKfptCp2uivFen8tMbtHDrx6zW
VpXYwPKDYP/VAJQ0OC88IO4RYpZS1tTysOwuGQIDAQABAoIBAA2BwYwSHRR0++os
bQ3vJ3okgoks0Rt7+8tjN69q78zVHCotELWU7ltzaKkyTpoZ4c1yTwP/+LDnvvei
7n6tk1DyPbz1FoWclykOS85BY6M2viYF5Vg1qF1oO9KSpId/QcLSbuJV58ReGpYO
Zi0lbquMxTQBrLTde98LPfMA/m1iDHCqvs6jFH/6iVKffxgruI/sTJMP8Okr1vKK
fIXaW164LAY3DuzD2QLSQ7i8vBPlmtrhYR/eGZ+MrlpgiEcmcbwX+NRFO2t9hXSh
fvayCf8BlPXs2XtuwCg1B+8TEV14CZEkDypxyzuFFIbKFbwmDxwlXHiFOxHZ2CjY
BOayJ1ECgYEA1+AR2jPIhqwc4PAyJJVXuof5nXWcsDJTiGV6VqWBtHr7ZJwRDUhN
r0K8uCS9JSL3UckVot7HynJTF81qOr/y/dcmx2RIRrdFrPK1kb5CJoiyPPUyc3Lb
uBk6W1mBgoOAFUPmR2xKbLomcBsmpBFHoWM2DAJmhEWfB7LHlmelMIUCgYEA2E46
R5Z2ZMikYnKVULgYzaOnbbRW+vsWQZSgCHuaFq7mrj3+EUCgsr0fP2Se1Swy8Es4
7r8q/Q4PridNPGXzVWbgcD8rcctUEDWYvBb3IQBeErt64ac69N+BGK+83tjF2BZ+
2oiMo5wDTZHHBGaUaBfIrWipBFNo0BboZUTX5YUCgYEAyA7InJ4GxP+2F6Oh5JNe
ZOhkpM79MbDCBxJ8KNZi+J5MYbXce6G5FKXVfRXXEBZyeyHOYkzxfKUsak+cleuT
Rjlgn8JI1Pg9owSezf0zEsD15VYatjEIfHkswsGVKx2w0oRFYYVzB4YP3y7aRYwa
BO+Lg9+poAVhVuIQ40sUJH0CgYEAmHr03Hg1t7A1KW0q0v8kBPqj0VL6qeyMcOiL
s88l/W2IEjaDPrg3UCi/uVl+GjoRIpF0beD3NfJOnW75JGWeForyFk6BmrNB7DdM
FvN9fJccucnNwvq3Nd3EzJk95D4docmh3P27Xq5hKbJlADYr0gFKJuwLkZAW5/Hu
G01fgF0CgYA/TSC8bOncH8mw4ZgtpJneaFQWRptAW9pjmYfu1xCgq5on3iXXja+g
SqOPJ6b3zhMfvrDGXdeNXLFMnEHX+vE53dOcSMSExHyOr1h8aIjtIxcc/TUwALkP
fcULxnmtzlY8qK43SjFS+ZTp/52kUA7A6FY4GovSrOhV+TgSQhB03A==
-----END RSA PRIVATE KEY-----
`)

func dopplerKeyBytes() ([]byte, error) {
	return _dopplerKey, nil
}

func dopplerKey() (*asset, error) {
	bytes, err := dopplerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "doppler.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEIDCCAgigAwIBAgIQMNDK9Az6Y6MtJH5dfR2w0jANBgkqhkiG9w0BAQsFADAR
MQ8wDQYDVQQDEwZjYXBpQ0EwHhcNMTkwNDIyMjIzMzQ5WhcNNDQwNDIyMjIzMzQ2
WjAUMRIwEAYDVQQDEwlmb3J3YXJkZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQDMkOdXyO5tpn3y5Q6FdjmTngRsZ/UA8YfrMtPwXnqlQaFb/PmTQr4s
+OhK0VurXrDgjVwVw5FOhzHGqpEjJ2iWXFIZjhprHXfkW+kSTR5TGVn4v88bY4Ic
uQomXk0hDVOLtgNTL4cs8YtaZCsZWw/aNDE8/1Vp6oRt1jy7o9/N3hedvFQku1rL
kLcEBRAm5GDmQLjljKRMvRRXZbt86TXqhhac3x1lyBZDaLKn7kglo6nyYzRz7Lr7
4Hq/hdXC5NzQR36luzvyvwJNmyWpSv5sN5I+tZOrBBrkRhHOCCwc0eqX9MHWdLbR
vwO4G1rGO8WmhbSnEJMbh6lCuN9lb0ZrAgMBAAGjcTBvMA4GA1UdDwEB/wQEAwID
uDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFAuciXlM
HcYmUUFsXjnS2OVSwuvoMB8GA1UdIwQYMBaAFDZ8IzkoppGR4phMh2EzyBN/9XZJ
MA0GCSqGSIb3DQEBCwUAA4ICAQBJCPIA/RLzUXKxNFU6GFlA0+tazzISNWNHiJM6
S4bzGja+b1rnR8XlH2QSWvq8akztFp9GjL3E8MMD6ZNORAJ1sq5Xl+HnuSB97It3
T53gzGbZPWI8fC5g1HlJ5OgNgXlhgC1tt+k3A8fYSRZ/unO+hAzg6wD6Sc9cRERL
MCPKOuSswpjs7HfLijV6utltMFagLyM9Lea1TUvsERBqSSiB8Yhh+K3R/y60O6oA
Q8zHmZHkMe6uGqGXeLbGhk96+sAYaXMlY1LALkqrcYzNQa67qP+MtWVxvgxhbm2M
mDctpaR1KgfZUHMnFgTBqRrxgds1WYLx5mVxd7g75YzhPLNkZ+Hz15/m3KXDTj3u
GiczsRBjqMwSCWAWlUP8FhRe5bjXMnfAtcU/a+yh44Q55NMs4gRIx/9m3BAt87kg
HrtMaOmUiNBitb5tAdnk5B0GoxeUe2aUDPLLzUg35eurBJj5Hy603vOCBAf0YnPr
JUE4qQnjWPe05y606jUk5NdWriM3I6t425J94Z3E7rhT1HTg8VcheDWGGTmORCVL
USTqMJX3/HspXBUewK8jlC43cU2j98q4niicf+xcWd/Cz0JJHQUyekdHh0xmEuc/
S8XI6CrxxUBjyBdb5ilRWSigTcE+HdjTddrg+db8ZD+AyaQ5EGbXiXF9aBX25BfL
Ka+4rQ==
-----END CERTIFICATE-----
`)

func forwarderCrtBytes() ([]byte, error) {
	return _forwarderCrt, nil
}

func forwarderCrt() (*asset, error) {
	bytes, err := forwarderCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.crt", size: 1493, mode: os.FileMode(292), modTime: time.Unix(1555972429, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICWTCCAUECAQAwFDESMBAGA1UEAxMJZm9yd2FyZGVyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAzJDnV8jubaZ98uUOhXY5k54EbGf1APGH6zLT8F56
pUGhW/z5k0K+LPjoStFbq16w4I1cFcORTocxxqqRIydollxSGY4aax135FvpEk0e
UxlZ+L/PG2OCHLkKJl5NIQ1Ti7YDUy+HLPGLWmQrGVsP2jQxPP9VaeqEbdY8u6Pf
zd4XnbxUJLtay5C3BAUQJuRg5kC45YykTL0UV2W7fOk16oYWnN8dZcgWQ2iyp+5I
JaOp8mM0c+y6++B6v4XVwuTc0Ed+pbs78r8CTZslqUr+bDeSPrWTqwQa5EYRzggs
HNHql/TB1nS20b8DuBtaxjvFpoW0pxCTG4epQrjfZW9GawIDAQABoAAwDQYJKoZI
hvcNAQELBQADggEBAFsRGe+n0Zcf9yrKavFNz25b32NrB+lnshBb+FTKMPDAmzrh
ftMdoSB/+HPcw4Q/kQeDG3lfiwwQbahhpu1o1DnOr8C8NP24xzBiLp7u88Em9HAB
BQ8SEXqtWq5PoibuWqNJrGVjciRu7/l//MAzvieQ8EhAuyxnkPClFalWwzayF05i
Y4z2rOW4N/P1rEsdoI9FTRjST6kSnhU7sYAErwJ4I9VIIFGvtBVFzRBo7YcWTynU
lw1u6FE4oQ8XGB1mHuuJX5jY40GqCkqHKhxdSeLDtQVPHBOp1k6+Pldr+h34kbhv
QaMyVXTI7gQrY0TNwQtt8eNnv7MhQoITHrvFvnU=
-----END CERTIFICATE REQUEST-----
`)

func forwarderCsrBytes() ([]byte, error) {
	return _forwarderCsr, nil
}

func forwarderCsr() (*asset, error) {
	bytes, err := forwarderCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.csr", size: 891, mode: os.FileMode(292), modTime: time.Unix(1555972429, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _forwarderKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAzJDnV8jubaZ98uUOhXY5k54EbGf1APGH6zLT8F56pUGhW/z5
k0K+LPjoStFbq16w4I1cFcORTocxxqqRIydollxSGY4aax135FvpEk0eUxlZ+L/P
G2OCHLkKJl5NIQ1Ti7YDUy+HLPGLWmQrGVsP2jQxPP9VaeqEbdY8u6Pfzd4XnbxU
JLtay5C3BAUQJuRg5kC45YykTL0UV2W7fOk16oYWnN8dZcgWQ2iyp+5IJaOp8mM0
c+y6++B6v4XVwuTc0Ed+pbs78r8CTZslqUr+bDeSPrWTqwQa5EYRzggsHNHql/TB
1nS20b8DuBtaxjvFpoW0pxCTG4epQrjfZW9GawIDAQABAoIBAEYMBDuKASKo1Q3c
I0nN/s8uV6NrQXjOO9VstSfkoih+PauLB0bGnuo1XQ1pfPNEXFq37OVC7zmtj3zQ
oRwhfW2nNTGs+BzfnVMjqb5ri8u2rZlAzME7JK2DKxeSSOTddFMtwxuz9ZyNJUOR
czSeeuIj5wxU/kFjXW9i4a764ULTgc29zhhdPzJiX1hG+hea1CPwv77PfcW/woqH
cGN5WfgmHRMfzY/vhVLGdgj2GME6S+cMbvywa79CzMzw7JAA9k4Ypf/MyahwTP+o
ATHNA7zOJBLKdxof+V3pWy+LG90QNg+wbWPTgs9XXN1+uJ/8SHxJmC1on0N1JvNu
Mi9RtyECgYEA8zC2mbZm0hVcTVufcnCVBzO1gMVIOTQ8MmJ9NItTPtAtSJr5iaZW
RJujblu4qqR1qTeEqUw0Q4kTM5lsAC+8+rG+rzfnYTHfAJuNqpPDU6IWh7b3MFm8
CxhIPqztrYcVCCAQ0FYuXvlZu/vS/qUtdjWACxt9OwE6yhTLEGBL8lECgYEA11dd
Fxf+LszvC69rn6rqIgH6EkTZWbr/+9w46BqfSquCQfmsWSwdAuBMUxmdZO4fYG/B
2lK5EPQ3RB4J8AezwsgcOxQKQKferafR5m7FGlMaRC981zCqgSUcjlG7Kssf/kUe
3+VntBEXAnsjVy547sE6iwSoudTeStmXF3+oYfsCgYA1Hn/UJXZiDw5hS1ERoyu6
Lf5ISU9UR2earc6haoldYAV0JX26Jl4TkFdrZJd6ln+o3ZqZjC6iTc+m5q0jgUnr
DGYVScW9gjIupMuV5b61huMa88kcg41CcyRcpFMqIyZh5vclOp3YWujR2diljJjY
iCkWxANfnw4jU9VjF1WfcQKBgAnRZeEjqucfWNbDjLie5kXeqTQkB3Tb3cfx5nZO
oGybHTk81OrL5Ba5e0FerZpocO3IqqH1m5J2T/6/D9ztvPhof0ECTOVdwf1Q5XUI
H9xvZYcuUxbMlTmGI6MpfssYr8C8DghPQUcocFAgpR/YcpMQJEcqUzcFyYzIFudv
XpH5AoGAY/MGJ2BNqocdqX54eTZ7ge+hh5PBt/wdZesYN1IvDH+31kzh8qw8hJzH
ERLRmidwT+B3ERcUWSh3TZ4IGY32bRHGw8XoC8IyggB8OM5chHcWnUj6es7RM/+u
rtrwV74Rv0mA3zQ4NY4vNMQp7OyOT+VGCFdzB9uaL5VQEZ2eY2I=
-----END RSA PRIVATE KEY-----
`)

func forwarderKeyBytes() ([]byte, error) {
	return _forwarderKey, nil
}

func forwarderKey() (*asset, error) {
	bytes, err := forwarderKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "forwarder.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1555972429, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrl = []byte(`-----BEGIN X509 CRL-----
MIIChzBxAgEBMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNVBAMTDWxvZ2dyZWdhdG9y
Q0EXDTE5MDQyMjIyMzM0NVoXDTQ0MDQyMjIyMzM0NFowAKAjMCEwHwYDVR0jBBgw
FoAUetoAMuApHRRLjgoXGpP1YwhT3q8wDQYJKoZIhvcNAQELBQADggIBACIRZsOH
McdnqqccIniWcuyk0LhswTfTYFMW0zUXpvcC9edGMiEf2RVa8/LWovWaNoXDJIrh
9FlQK+LFJr0wOAJJ2aiyEFaGENi+xlFF7Vs101iDZA0+sdLZ21RRpkKNh91/H8ki
waiem0CfjUS84q5zx0eO+0AoU3UFeuZI7kH7m5dGWGEoBGMCCbpJVXj7MIL6IG+B
tbikiOx8oOp3UfMl9lvyAfGOJkstLBxrBv//f0THvBbghn9PFT2XKUu4AUeaJUu4
xs75NhdocTgt86IwGnTr+KGLP7QpK26D6tGMyMFJ9Q9k5B+Fq/eE+6VRxeBdyAv0
FjwQpIsbhWEENXWmh8FU7qK/HLFaMPxpFiEiJ+UMpSm/VZ2zWktstBmi3yT4fV6/
bGufCSTUU32VmKZdjSvdq7w4tk0r5EeUbq1K4LdjlKBvXNB+iW+FN9ms7Zi1bja6
pZVrqDIugs8OpJLZ8kg59G2Sg0hhdFq7s0JzlQIXk5bOl/jr/B1pQIRQa3opA2Qs
bR066ljXfzcKml3AemVLC8pDGZwQJv77oQdgI7JagISNJMx3mCqHA+a375f3LyYr
sP1AW7nSQst+k+ftljMnqyLGqLb8dTdeGL9ZN2fOXwpjL1GU1NhEF6+Cihcap65t
WwNB6zLeIdpM0mGBUKs8oO0uMspNZ/+DnZnD
-----END X509 CRL-----
`)

func loggregatorCaCrlBytes() ([]byte, error) {
	return _loggregatorCaCrl, nil
}

func loggregatorCaCrl() (*asset, error) {
	bytes, err := loggregatorCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crl", size: 930, mode: os.FileMode(292), modTime: time.Unix(1555972425, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE8DCCAtigAwIBAgIBATANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDEw1sb2dn
cmVnYXRvckNBMB4XDTE5MDQyMjIyMzM0NFoXDTQ0MDQyMjIyMzM0NFowGDEWMBQG
A1UEAxMNbG9nZ3JlZ2F0b3JDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
ggIBAK2TZEJXLrfk8RtzgAU7b7QGeaVpdqpBPBXHmj+GRhDpd6D2CbdmE7uQyeKu
2VjDu2sfZa3CVhc05qouVlg5ySQRZox1cL+juxTxGKotUcw38a/SyFTR3QYTwmri
LXeCleEGXRP6ODKVRftQJplwqRXcb7L3lsvFV8zkRbRWWMBpk/hsGVNl94o1h+sU
I6alGQR6z22+yPFUjytOWDwqFxS4eKRcgv/VWZgXfkP+DALt2+5S1LHSFGbJGXR9
jTq/Oh9U1ZkwDVn55+3sHUWTSKzb/eVOEbMej3J9kL26Zc02h+suMr6aLTpG1ig7
EvOkjD/vaTEgAdbpRi/PbbC2j0bbkSjtqj2QQB/q3k0aRetM/soH+ilIx5REOJv5
CpKRFTye0PDW5C01vw8glKdu4IOyjgvbSm4WEUvvJY1MaSPnKLZK3pDguZD67Me2
WAkii2xKaeadw7SwOzl1ntjm/Xab6uPjfitCjuRD4K3RM42Sy/HvGWPBPGBzCBco
tbsowUjv3pgvowGCLSDkvDH8K6wKX/2GyVENTw+FlQZFYhKGM4bkpnq4ueLteS0z
W5hjJrx2SmY1Vf8gvDenrB/zgW+YBNXkYU+VI32hYmdfILVmZMruwFaiUkn8rN6v
xYvySal2sF0A2T4lJpOOTyrgYR7isGG8cp8Knz0UHyIdsYppAgMBAAGjRTBDMA4G
A1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBR62gAy
4CkdFEuOChcak/VjCFPerzANBgkqhkiG9w0BAQsFAAOCAgEAVjMRMg1XF85j70QZ
yCYI38/5KiI/4Fb8drfSjqRIiGCHtE++LPjM8Bq1uvdAAIHQLXVaELVEJxczly42
cEL8XbmWWa0Ly2Pz5CfGzeqi8v7dSd467dRNumOmm3Yn9C94t/mKbw0PyNlJKyY5
04quctUrSHVBREQdkcui8l4se/6z86w42Q7oDsbHZXsK3FR4L0eegC0fdgJjz5z0
0R0ExcLfUbX6aosXqjUUPAS3FFvd52bmWlI5UF1fg1vJiHUJTLDHR8RgiP/zssvF
CcRiyrJhS5kQt5d20NICaUw6aEGjsweNrSfGprQdJCFSmMk5iBrM4qAjvl7ztkFu
IMdK6LsF+bMexMt5RvADOG7QpQIBmyWTH3XVXZUouFrwK8roMk/VbvYrX3Q0IpkG
gNzv+8IWv5sJM1AQK+4cb7l2ChlmKfkbETBA1oQ1EmbwO5nXcJx+w+ZBzPQKdn4Q
CfSuGSfLensOCK0/iFwzt0kPfdAqMzdmqbdoya75+gM1qSWvXTN4geqtMbSboJYU
J1S/mPyyNK/O5ppfWrEy2nmZ8qoJuSsdzd8li213QRDTNj3+pnKe3uahnH74yh1N
nlghPPvN/fWMid21aZ54tc0w60zPbaavASTwTYWWCjdRLIJD34ZW6WcSxXtXjC/j
GpWWQCny7oi35prJSEEaxRPhtoc=
-----END CERTIFICATE-----
`)

func loggregatorCaCrtBytes() ([]byte, error) {
	return _loggregatorCaCrt, nil
}

func loggregatorCaCrt() (*asset, error) {
	bytes, err := loggregatorCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.crt", size: 1773, mode: os.FileMode(292), modTime: time.Unix(1555972425, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _loggregatorCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEArZNkQlcut+TxG3OABTtvtAZ5pWl2qkE8FceaP4ZGEOl3oPYJ
t2YTu5DJ4q7ZWMO7ax9lrcJWFzTmqi5WWDnJJBFmjHVwv6O7FPEYqi1RzDfxr9LI
VNHdBhPCauItd4KV4QZdE/o4MpVF+1AmmXCpFdxvsveWy8VXzORFtFZYwGmT+GwZ
U2X3ijWH6xQjpqUZBHrPbb7I8VSPK05YPCoXFLh4pFyC/9VZmBd+Q/4MAu3b7lLU
sdIUZskZdH2NOr86H1TVmTANWfnn7ewdRZNIrNv95U4Rsx6Pcn2QvbplzTaH6y4y
vpotOkbWKDsS86SMP+9pMSAB1ulGL89tsLaPRtuRKO2qPZBAH+reTRpF60z+ygf6
KUjHlEQ4m/kKkpEVPJ7Q8NbkLTW/DyCUp27gg7KOC9tKbhYRS+8ljUxpI+cotkre
kOC5kPrsx7ZYCSKLbEpp5p3DtLA7OXWe2Ob9dpvq4+N+K0KO5EPgrdEzjZLL8e8Z
Y8E8YHMIFyi1uyjBSO/emC+jAYItIOS8MfwrrApf/YbJUQ1PD4WVBkViEoYzhuSm
eri54u15LTNbmGMmvHZKZjVV/yC8N6esH/OBb5gE1eRhT5UjfaFiZ18gtWZkyu7A
VqJSSfys3q/Fi/JJqXawXQDZPiUmk45PKuBhHuKwYbxynwqfPRQfIh2ximkCAwEA
AQKCAgAEXLLlU+mRp4hDp1htSTwaaxs9g/P+fVs0NOr0c7xpCmT+P5Co8kDGsvHP
55MAvxKDs6tLfZnKRYMSfc2fs/wREvrfxsfJmSTHdvOmuzLWDgXd5E8yin+ienal
Vv/LhBWeLRnDucMVyliS40XFD2bAbOTFu6Enh9MYDBiQWqcqVrzoPlc4mFRrPcMn
rj7jHj0NtsRlvqiwH+7lKLfg8zHXTHeDset84HC6+MQsk0LcA/xF9gDwYxYuKxmf
qtQUyN9+EBS6H9IGE9i3SvrFV9k4tuKfk6GwPbFfMDal/fw29wrdZzDRR3ChiUwy
gKGOS/FWXf7nxCUnsH8aDn10NnJNS/HGApY12esafbecejgy5IPJNM9WQS9crvIO
aIdFw0y0X4h+qtZQPauYAbZ2foewGlbY9doOh56JCIDmAKmf2xudRRZgK9MNVS38
1umdDPS4eHME9NSzDvORElW9jOitVXc+QOvMTz5Bg+P/D2CZFnwyI+rDkNUBhkxA
+/OsEzSgY84RJ3BbkimEVtotM3fYGDiZ3WvVSR0y4mmweJKM29dN3DPtw0vEh2HL
FxelSL8AoKy7w5FmPmgJfgHq9GV6Smk94iNMeRpYbMeyOiZ8+xUCVn2ymCTg5pSK
23ty0ciZHlArpp6eZQErTQMvwv09IE6bk7zPloVWqnynOKOmcQKCAQEA4rELRbT/
ZNXoP8hitNa2GHfnuTQGBZyO5AEMISpuuBBD+9mbwzuh1Tnly4NAJLDQmnSby7Cp
Q3x7Y9UiDMDTmTuDN1SAHAg678sG0EmDfl+alEGIW0t97fKVnsXtu18FuRs97MSx
ouWof6mJTKWiagAp2R0beVmHTj0UzYgQiGQD4R8ANqYyGEYiDdf9wRYdCZabGRqs
pTLnKUDgeO1jH61wFVLuL23gLv1fMdind3aeoNqmfrt4JVk2YGXX2tUH1GPxTmzR
sfAO1Fned/6nO/HURqmbhQlVxxI0EtGukr9aWoIbmJpEyT2TOrIYRFsYzD3SF/Nn
aiasSB5Gwnch/QKCAQEAxARWzML4NEgdHe9+PYnFBrlJu/WwyB+x3CN0tPPVuxp4
1TEfZoH8Eb2iXiplbPmqYrcoJEVPDcqmGspbJtiSt2Srbb8HQXi70RrpU7kJ+4+K
ptlYOJNG0qmglyYIIrlLF+FBhx1iJY6xGLEqhYpFdCMxm6x4N6HSQeTEdh80+1b1
uBnAdlfkoJn6RkHsKiKHENf7X0YUo2kZCHXlGO0UXzFsh9wGhGVfq6BCIgnMpMP0
OkHT33UYzzMlpKBwdd3hzBg4dhAQZkKVVD4AxDRgTUSUMGYk/Vj06k4f9keYymn+
dByKpjjo8QoPr7XSY0o9zb7lswwlO+qgDnrDN/bv3QKCAQEAwJ7dTCrixES6ZtAX
hz/WVO41uPoKj+QayoRVUS0kDUTM74hVQUw/U9Yxe38YFtUjO8sPwsFm4hA5LHgi
yaFjaxXVhkNH5AneQnlKXdvJXq1PxN/2RFTeOTzig5n9SjQQwdvy/2eW5SqtxWRC
ZR1s5xMie/iuqqs3PHTMY2RVX/9UCIr1/Hm1oUiekRLR7Kqkm8wcF/XBc1HQeA5H
bpmPm5Ac6BGikCyVzHfA1rMYgXsKiPWheZhEG8A1Yy3Gf4x6ba9KkHAIsmCfyTJf
xahdY6M106E0o5NuDoxaMQ94ffsYhEV/u2iCQFkQ7FP+KL8bUBjLl0xcuCcKRvFr
ALyH5QKCAQB/vWgnlqOTxq8a9Bkr112L7TINCKcFNAp/sKd8yS6u+ShnntScw/bW
ROPMRArHAskz/bJuOLC1ByxKZzcR0K+ETlmdcpEy7JBRTB1kT0EfLEMqSpfAftH3
tU2PUtyYbHJwhH5kpBRy71OgCMzyK9LpRYotri7F6nIQORqC9AFeDiShrj6LoOnA
c7fzE0DpkIi+xFHvm8cVWwdSSSpcnRvakWXt/8hLfZjkStLuRb6UXZMKaB3AERpy
5R0R9PB1D3z3uY0J+5wEWD3ioWl0c8GSeS+tftN6Ov+YtgMER1JeDschOfxtKMc9
VdY1JuONizNNoqskjLSzIErgRMZ18ToNAoIBAAtbiv1h6/3y7MENNfPIEE+BHg5Y
ExtzUTq+uCE1VvbnZ8eXEZTguWlNW/Lk8lbZwS/7gJIPUdK++DwwuRBE4pAPbAqP
jXkINmmKTRuAMi67z+E5hLyY3OKMg96YzP4mN9+5dZ9v1jG0+gqOVijKgJtALZ7w
IA/Cd4FT/UppUItwn0RuUbvnChNWdHs55Ph56CC6pPnbrUEk5dtaDeISDwCK5jxr
vRAbeYa7irmJqWarzIeKnFb1C2+mKst3Bem8hWZezuUF+weXrlN04VF+olT4U+I3
MU0C+iK8ULgRmBu5ahzeDsQsdeCzIQWGKoNXEP+gcmSM1kdCOm/lF3cqOf8=
-----END RSA PRIVATE KEY-----
`)

func loggregatorCaKeyBytes() ([]byte, error) {
	return _loggregatorCaKey, nil
}

func loggregatorCaKey() (*asset, error) {
	bytes, err := loggregatorCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "loggregator-ca.key", size: 3243, mode: os.FileMode(288), modTime: time.Unix(1555972425, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metricsScraperCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEMDCCAhigAwIBAgIRAO6UUYL5Kl39e8Uqgxy0RW0wDQYJKoZIhvcNAQELBQAw
GjEYMBYGA1UEAxMPc3lzdGVtTWV0cmljc0NBMB4XDTE5MDQyMjIyMzM1NVoXDTQ0
MDQyMjIyMzM1MlowGjEYMBYGA1UEAxMPbWV0cmljcy1zY3JhcGVyMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyucUsitk/2JKlJcEpdPjGafqY5oIDCDM
EfQd8G3IWHXAR/RGoEMmjR2fln404fQ9/SQJlMGeqjOsZDCSKr/eqC9BmCTA5UqB
u2rc6Jp9V0q0QsntYyxaoTq/Hl4ZwOayyIYP7exlQtK+T/0WEZsDn0Bl2uzqKMq7
A55nBWocgZHZGQB1EriRI1LJ3gG5SZpqQosWfVNA1EGRfG5OacRwGxGhl79qxe6O
H5vLwolqA9JV/x0zvE88eceaW0VZZeawq5ClbZ7rB268TCtjnWyw2HZTClK9z9lN
x3P/hm0/st4YjuQ27OT5yi1UPfy0aNKWCuB/ZQBHmhIDV3tN2NmegQIDAQABo3Ew
bzAOBgNVHQ8BAf8EBAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMC
MB0GA1UdDgQWBBTpBa/ZrQUkD1QPPdnqEDowedspRTAfBgNVHSMEGDAWgBRVWxhI
mk6s2+LYWDh+5BesD79R7TANBgkqhkiG9w0BAQsFAAOCAgEAxrcI1hdj49ifjlQt
RzTvpFA9AT1SvVuDTT78emEq/gzmcfr/lqkRyi0K2R9wsE7wG2BANX/SjsMlJLmb
VbEkAr8BGox64FjIiNUIJp+VhWgAYxRydZiaYnYZLcIsvJdWtc6fky0sT3NZhNJk
3EC6kk4ggurjc7oZBcIUVDYcnov8FW9rhKkdK2yxCxWc5ah9O7hXsj9Xy8SWjh+I
/LJjBD0uxNEHIkLkWlLDYuspW/l1r9PksOin1c3GJA+YK/i3SKVduse3qhr854jI
xqkyyIN8SWo8dS5twpLFFu2vZd1MzNpLVdi9UDsG/vCnL/8aRnOdGqleUAVGDy1Q
RX1/kdwNWdXHCmMw39LuCxWGnjfCugL5RHXADphEVH2IBbkhueh7rK+guqWRCSnS
ZryYkrUF2eJbZ4W6WEneERlmqaz16eZ/l14EbvpkEKOSCpZGOXy5+ViZR3mYKC9Z
SvzUeKz1m060pjrb2xYfWFknZNMx0UOwHKd34h+ogqQqwU0LbSDRxtxoIjxxDOmX
H9gPM6OyDqzFm/AFzL1TF8D99rAd3r6OnIIRR45PI1hKWBKiGRXv7QfAUsk0XVRA
rmytEuTooVP9+0c4s85f/ZzPaqV6EvuGKdkc3a7uhuK6hAkcn9zSDjD0/t03r5hV
3emMcsT9cH3WGJQ1qvA70GApxw0=
-----END CERTIFICATE-----
`)

func metricsScraperCrtBytes() ([]byte, error) {
	return _metricsScraperCrt, nil
}

func metricsScraperCrt() (*asset, error) {
	bytes, err := metricsScraperCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metrics-scraper.crt", size: 1513, mode: os.FileMode(292), modTime: time.Unix(1555972435, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metricsScraperCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICXzCCAUcCAQAwGjEYMBYGA1UEAxMPbWV0cmljcy1zY3JhcGVyMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyucUsitk/2JKlJcEpdPjGafqY5oIDCDM
EfQd8G3IWHXAR/RGoEMmjR2fln404fQ9/SQJlMGeqjOsZDCSKr/eqC9BmCTA5UqB
u2rc6Jp9V0q0QsntYyxaoTq/Hl4ZwOayyIYP7exlQtK+T/0WEZsDn0Bl2uzqKMq7
A55nBWocgZHZGQB1EriRI1LJ3gG5SZpqQosWfVNA1EGRfG5OacRwGxGhl79qxe6O
H5vLwolqA9JV/x0zvE88eceaW0VZZeawq5ClbZ7rB268TCtjnWyw2HZTClK9z9lN
x3P/hm0/st4YjuQ27OT5yi1UPfy0aNKWCuB/ZQBHmhIDV3tN2NmegQIDAQABoAAw
DQYJKoZIhvcNAQELBQADggEBAIDUsEgin7f5aE6yc88bQnXk6aUJSrZIMHj8/oC3
JgMjpkG/sL3NW+a7FOf00VfWMyUVl6l99ob/5//BL83ALVRkbUV6ns23WRS6dftc
msKFRB5mYAcREg5XksrSHUBJV2burFKDAog/FKtkJyDhkL7N2Fm8huZ2ZoE22Blh
X7REFaG0kzTkEnwxgUaxtpgDMzvwqS2fgojpXS5EYyKpvlkLXtuxNkZWuxsm+G6p
sTZTUJQ/UIudPlGp2g1Ce61cJoKs+m4VoFHMmDsjr/NH3t2B+HBWm84vm5joJdI2
57kadbNqqMLoUw8XeLMi9M9c/bktsXvwg8E5GumwOFGmilY=
-----END CERTIFICATE REQUEST-----
`)

func metricsScraperCsrBytes() ([]byte, error) {
	return _metricsScraperCsr, nil
}

func metricsScraperCsr() (*asset, error) {
	bytes, err := metricsScraperCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metrics-scraper.csr", size: 899, mode: os.FileMode(292), modTime: time.Unix(1555972435, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metricsScraperKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpQIBAAKCAQEAyucUsitk/2JKlJcEpdPjGafqY5oIDCDMEfQd8G3IWHXAR/RG
oEMmjR2fln404fQ9/SQJlMGeqjOsZDCSKr/eqC9BmCTA5UqBu2rc6Jp9V0q0Qsnt
YyxaoTq/Hl4ZwOayyIYP7exlQtK+T/0WEZsDn0Bl2uzqKMq7A55nBWocgZHZGQB1
EriRI1LJ3gG5SZpqQosWfVNA1EGRfG5OacRwGxGhl79qxe6OH5vLwolqA9JV/x0z
vE88eceaW0VZZeawq5ClbZ7rB268TCtjnWyw2HZTClK9z9lNx3P/hm0/st4YjuQ2
7OT5yi1UPfy0aNKWCuB/ZQBHmhIDV3tN2NmegQIDAQABAoIBAQC51NCAqfvTZrt1
waaxFhH98mtak71hFjyxCMrO5E1Er3vOquxwZXAOeJ4sICTg+Wg4y2O3CWn+6lqu
XEnSu236zWUfKjI9DnMpKqNuqee4JiRYs0YmuX28Auj9sCOYJ/KAc0BtoT/Q5uEE
s4Ad2cKEfV+MFcYUXDDSDKbAL8Ix67aZGrfhWGeY6CGuY7bCpx5YUpMiLIaU1MQI
X6swlmXnrSXBpo5y3RsuEeN7xMhD8CmX1mAwT5kBEGdflcWHkJZCOtr0/ORkr/rr
on8SSKZDzJpuKeqZf/Fr7KGl/1JktVLha5l3uxCJcPCQZxKclA5Vd2yAOLZfrLIN
mfclU5DdAoGBANL98cq8VT2zYV6IgyPI20+BZ1Itmd453jz1hajYPNAPyV68tnoC
oz9wpV/GjOb1cnJFIiCzu/lkU3sc987TNsr5NmTBxcnWadO8DSQwjyByKh6fkKHM
Fa0q7HGH125NL11C1am347cwUZSXouioB7gArO8HdRrikHcuiP5AHtofAoGBAPYv
Yyj1Gw0KplKFpR4v5RJjiz9TFQqvu6aqqNf/QyTK+VFduQJUKGo57PFLKmHYdV7J
Eyir3OaW6aJ1Bctg87qkWH+3t+heyR92zsQQfYe/ii3PvWs9ewP7pM1DdzKXxsv0
ANKrkyYQ15t1pUlzB5A59Cj8n8j4CArLxt5OvbNfAoGAV150u2DVY2FeVojs1Oqd
dgS9xhe/+Xe5AUEiAdLZC8cdua8nWMqy0thQgqJzQkgtBgh+o1AJ7LGQqBBMxUZN
ECu2TG64+mVhGR5ryqqY+fSMYHXurDEYYMa/dhusJ66qiFHerBLLptXJUmCgQvsh
hx4wfiJ2aZWcAN4yOCZRID0CgYEArSQuzUN1PvradvdfZZext/kimerIxbdKdrFY
BnGUu2+1YTBVSfn+YpdSuXFv4VjnUz5/pv8YYWSJ9KPw61TIld+4DjsbsOXY9bQN
P3+JicuAVy/fvGiE+Awnn+VvE7oDKrX1TjU1THRT7xYSpVGtZBYeTiU+C43FujIP
L5KZgGkCgYEAgogdutgdh+xQCNeH2/8cwQGQ1MPNvq/qL4DcYrCdp7LCxFsPSBer
qv8IJ+GBVXechFsYImIpwRWVuVF9exIzhP36zzjDVJZRu0xSD6CNpvMsVASuQQyc
x13yCiC0itKZl/xjLEvBjpVlvQHmCRV0V6108VsFicib82a3Pm6mlyk=
-----END RSA PRIVATE KEY-----
`)

func metricsScraperKeyBytes() ([]byte, error) {
	return _metricsScraperKey, nil
}

func metricsScraperKey() (*asset, error) {
	bytes, err := metricsScraperKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metrics-scraper.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1555972435, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJTCCAg2gAwIBAgIRAL3SDeOF6NDiV8RU4nbF+NswDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xOTA0MjIyMjMzNDZaFw00NDA0
MjIyMjMzNDRaMBExDzANBgNVBAMTBm1ldHJvbjCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALbF5W8MAh2ut8pvmsZsKt9BaGFjEOm4kcDph5ipBTLI73CW
EUgT2r4l6XsnVu4Ay5Dx2THf/rM2kFypIGNqFnmJpb56f/Ii7Z+T2FlQXGGF3CPy
qA9ct+A8OGhsSGshkeBwwbaR3V9AReEKxDFvgzPW4LpudOnITM/CUTQnbrVhHshn
UlktiF+6coWsnlPtGJ6nL9+my7DefVD2yyENsxSI9NFg+Crd5JAtTQW0gDe6A6eT
Qr2omme+Sp9HF8xFkgUaqXSM3mkML6FS59z8DN6n26cYjqwcILEcDpVsD7DcDyqA
70Q4tvMW1Jmk9qCq9iE8//l7Zuhwcv/pf5yaUlkCAwEAAaNxMG8wDgYDVR0PAQH/
BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQU
/vAiK0QSPZAtK1Yo4X8/T+VAIH4wHwYDVR0jBBgwFoAUetoAMuApHRRLjgoXGpP1
YwhT3q8wDQYJKoZIhvcNAQELBQADggIBABzfnms+sUyvkkay4k/Fq/7pENUb8Jdp
IoaZjNQG24XLUVis9Ley5qucONSfEyNOIKmOjFhP+BlTaUutV+kqNk4HcRyxkSxc
SD0OcWH125jmfEtqBnzKEnnIMw9wq5YxNzIQEWj5+dORVxjLcRzJyAnSWhMj6Jwn
ETck1CuTwjCm5BalBdWse9hE0nHu+iWFfRUvQQfi9fAlpz6LH1Lqz4fWsWNjYM64
j9arw+vxlxXVUuP3/bx2+5n2CvJVw20JTtbeG8KAbi2kWvKX+UVJy+o9OXZI+Ucq
8X2M8d2ex7FXvLW2di3CnWpmf4FVNkw559nRBtB/oQqW24M0fTa1IkF9TbwXjNEx
3rh8ltR3+rjPojUozH3kL/R4h4u9s59NkZe38HlEpNU236+hHBBCzkuoVGPBUTiG
w+k5TDq0sUHXipczBfJXTPrNAWLm19Gh0+zWh+7tpFMpJAEukAkGjJhTffCXAjrK
JTYi9kSBAwvEuo4UIeBi5gncGWOWkN7JnPd8UsLVxiPrCKxel52Td+r8B98Yyt7W
tOStEJm3hDlX4GvPmV0QxIqe1gVnD3G+XwwGlmGspogspaI/4NPEUkREf3PtFPuw
+EjZps715oSX0y4K2H9qgZHBk/65Vc8qq8DosMjqcjsMQGZGJB4YqfO4MmX4ZP6C
Jv0FSMf+xxkI
-----END CERTIFICATE-----
`)

func metronCrtBytes() ([]byte, error) {
	return _metronCrt, nil
}

func metronCrt() (*asset, error) {
	bytes, err := metronCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.crt", size: 1497, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAxMGbWV0cm9uMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAtsXlbwwCHa63ym+axmwq30FoYWMQ6biRwOmHmKkFMsjv
cJYRSBPaviXpeydW7gDLkPHZMd/+szaQXKkgY2oWeYmlvnp/8iLtn5PYWVBcYYXc
I/KoD1y34Dw4aGxIayGR4HDBtpHdX0BF4QrEMW+DM9bgum506chMz8JRNCdutWEe
yGdSWS2IX7pyhayeU+0Ynqcv36bLsN59UPbLIQ2zFIj00WD4Kt3kkC1NBbSAN7oD
p5NCvaiaZ75Kn0cXzEWSBRqpdIzeaQwvoVLn3PwM3qfbpxiOrBwgsRwOlWwPsNwP
KoDvRDi28xbUmaT2oKr2ITz/+Xtm6HBy/+l/nJpSWQIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAGVUts9GK5ISKBwaUW9Pv8UDZFcYKLSiUCwoAZDSqW9N24RzA3xr
0ZaTETos0cZyL5hrJTLACNxTGY0B2+erhFat0GMY47b9xrUE5zbChyoLSaTKgX+o
aAmClWEZieT4qSbKC+i44xgbkD/JR3pj2vzv+67CV8tA/JoY+rmw5tprRpnA7v53
36tzd41q6sVpPV52SonzSE8R6yqLhZMAbp8ENO7O9N792dVgjkWNOiqL20SEac3c
c1l9SoSerFMoNNJOfMDFNZurLpi38UIVczTvBLa25n7WSQVvbSo/w7dLCHBKmGXi
EDTQSpusIYIO9k++4nzXjvIqo9rsn/eTz94=
-----END CERTIFICATE REQUEST-----
`)

func metronCsrBytes() ([]byte, error) {
	return _metronCsr, nil
}

func metronCsr() (*asset, error) {
	bytes, err := metronCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _metronKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAtsXlbwwCHa63ym+axmwq30FoYWMQ6biRwOmHmKkFMsjvcJYR
SBPaviXpeydW7gDLkPHZMd/+szaQXKkgY2oWeYmlvnp/8iLtn5PYWVBcYYXcI/Ko
D1y34Dw4aGxIayGR4HDBtpHdX0BF4QrEMW+DM9bgum506chMz8JRNCdutWEeyGdS
WS2IX7pyhayeU+0Ynqcv36bLsN59UPbLIQ2zFIj00WD4Kt3kkC1NBbSAN7oDp5NC
vaiaZ75Kn0cXzEWSBRqpdIzeaQwvoVLn3PwM3qfbpxiOrBwgsRwOlWwPsNwPKoDv
RDi28xbUmaT2oKr2ITz/+Xtm6HBy/+l/nJpSWQIDAQABAoIBAQCd24AUj/+H2W49
tnSsKaJBnsFjU2e5JUMlpc0KSfkGast6pvIYGaXUkvP7/Pc0qpUnA+r+C6N074xx
q1Ug5/CvWfY/9Jdq70XijJPQV/rh8/Y1ShBi7EaXsgtaDSPi+2R9v4VfhM34xY9V
FbJrrA9ah50jB+GMRQYqbn8qF2Cj396WqolDQmv04NFI1afa6kpq9roToeEll09s
zvwStAq9ZG9x6Z9SE2dG3zDn1lw+kCnIRob5o1C8kmJxFVLkwJFWHPduTYJu8e2b
iZ7Rhmrip7tca/F3TfvnssbA35cbgrjDXmPJ3+CyLXFUCKC3foMDLQBfwLO5pqd3
f5puHMD9AoGBAMtvDyFN6JqRDiZUXMnBxJ2BmgX+3gK7/sBWHNF/cdK/Zls6OBpi
lOw7+OVIfBvU10Wek4hDPY8deyadIMtm28uDfQZKWMDsPR9wiLkNz59UaZi2p/mI
SpFZs1BpXFMVyTnH8VFnAdM5QYN5AZUdI2g3Bv4PiProPtsm9YUrTjO/AoGBAOYA
JY0IYEpb7GNzN6FxhFYFfMMAoQklPzxMdlXehT4Yhni6DDNCPwXgtc9/2/X0hS8A
ezKh/Z6YioXXiZqkvix0XzGxYjiYPyEimK87QtvYMbTQ+Ul93AwUaTBF6W3nwdgD
JhnG0cI+cGT66OjyQ1FSHt8JIqZse/W4dPiqmp/nAoGBAKCKkW8f84tfI8J92wfh
YY9HAszueDfCMmWIz49IuwOsxlMCG9o+p/XR0jbnQAIaspQfc6AaKE9z3Yb4gzPh
hV0S9CxtqaL+C7Ju9YbMbmf3jqnUo7TZqLcSCd9QdmqfC8EMl9U8rAUL7zaY3PXX
G+UXX+5JRjlz5H7APQuNxFYzAoGAFKu6tDwme0hbrGx0eXv8SsbfeZ8a2fmQ/1hX
4kvHaddGbp857XlstJiHfoidOjOprJm8eMZ6RsCq4nCGm3Fm7hPfYlXw3+k+8zlq
w4Tt81gwz3FglixLlIJZGc+OtSP5FfLif7qQq4Z1D35FZHoxdqOMxrrJdG+XjHPx
f0/F6c0CgYA1LVTkjUitEly1uo1N5tfhNnB+AgxDYhhyAk1u7RnunwlX4jIbIxg1
rsFmxmnAzHxLIyY5pV4Y5LX7rfXw6y9Vjkd8/ufXvBLj7HhxMRKzLYfNwLxLlzpN
BXtoJB9s/HqHT6LaLicOc5U6sOw+cu0eKicx/yNaTPaQciZOFHuMtQ==
-----END RSA PRIVATE KEY-----
`)

func metronKeyBytes() ([]byte, error) {
	return _metronKey, nil
}

func metronKey() (*asset, error) {
	bytes, err := metronKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "metron.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEKzCCAhOgAwIBAgIRALunpnxFgTTG6CWTgdRbDJ0wDQYJKoZIhvcNAQELBQAw
GDEWMBQGA1UEAxMNbG9nZ3JlZ2F0b3JDQTAeFw0xOTA0MjIyMjMzNDZaFw00NDA0
MjIyMjMzNDNaMBcxFTATBgNVBAMTDHByb20tc2NyYXBlcjCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKa1uJcGkFzKyPFCiRh17a4vWxOkTT8DMdrDv8xV
pVGCttcn1UM0/mNVmyZhGkOn+ElGIxHV0U3oLsniGvAKEZh/NQ3WbDuMBVQoviO5
NU6lsYHwDvUzj4dJtUUTNfRZldXsDlrkoQuLCmMtioGEh8ZujJq0H2uhN5a0bYzg
OhRSIrVFry4vFl2w1H7RFNn5pvZBa/jY1sGRypnl7jzNPVnd3JCVGw92xXq05bIU
2CpjlruFQFYDWmkeqoDgD85sL78KB0nDluuNv3n2gOnh+B2BOm7The9vR6sTfr2/
Qw9yNRvmuVmSHAsjZl4wKwNB5Z4Zh4/vDt0AI05qKlIrhfcCAwEAAaNxMG8wDgYD
VR0PAQH/BAQDAgO4MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNV
HQ4EFgQUXq4fUYbXSYfRIDXIY0gmrWV27hUwHwYDVR0jBBgwFoAUetoAMuApHRRL
jgoXGpP1YwhT3q8wDQYJKoZIhvcNAQELBQADggIBACSbIykYL5nr7xpaMbmPV0pb
kzhuRJK26DPfpjfGn6sFvkjRX5kJwWKNwaet4adXCjZ8Ha6Kh6O36qTCP7ICklYn
ADd/5vLGieeXTKk/oiXmSeQygSep+RvkUQZvuOXkJmq+wzym732pSG3lAPjMhZ/g
A4zCDvCHuMGRnnkn7zl/iu4xs2kir6p8Gd73+VDjNFdfn19Zphg2Zcmv/QgpYQ4W
2+OyiG7q5aVPVnm9cUatERAEvqqXmrzzBxTIXTJrfAL1UuN6sVoER5qPunv4mznt
k28gGTHdjvZlo2SpZxEsk/LdTPiXEEw4rowvP8ESmYJqlB5sVv28iYpvDbhtLFCu
hV7NKp+uniqbFlPL+SuIa9M7iLS43U5XcPMCIcFTskUWcWQZfbl81MbSWUnV9fYl
j6sc+w0LTLWEE+MASzeyC9kJdsvboR0n/Js8SsL4MF7+6cMBw5q0X285T2CupVfI
BXwais4IuZyO+FSACgz+ieR3J2Z0YaUAE8khW8nGkFm3NWArWCzfg0ubdhS8lml3
33y1IeceL3fXoaOMhla7x6qlT9A0+p+cz006h5qBKT9lPabsACPTjI5Gj4sWhwIo
1DdJjAyNgwht9bRlS+1U3dResBp6aeXoT0uXeJI6NcIAcGKaOF006/BQxgpWCBhJ
JL+aRssAm3oNpWzi35Gs
-----END CERTIFICATE-----
`)

func promScraperCrtBytes() ([]byte, error) {
	return _promScraperCrt, nil
}

func promScraperCrt() (*asset, error) {
	bytes, err := promScraperCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.crt", size: 1505, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAxMMcHJvbS1zY3JhcGVyMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAprW4lwaQXMrI8UKJGHXtri9bE6RNPwMx2sO/
zFWlUYK21yfVQzT+Y1WbJmEaQ6f4SUYjEdXRTeguyeIa8AoRmH81DdZsO4wFVCi+
I7k1TqWxgfAO9TOPh0m1RRM19FmV1ewOWuShC4sKYy2KgYSHxm6MmrQfa6E3lrRt
jOA6FFIitUWvLi8WXbDUftEU2fmm9kFr+NjWwZHKmeXuPM09Wd3ckJUbD3bFerTl
shTYKmOWu4VAVgNaaR6qgOAPzmwvvwoHScOW642/efaA6eH4HYE6btOF729HqxN+
vb9DD3I1G+a5WZIcCyNmXjArA0HlnhmHj+8O3QAjTmoqUiuF9wIDAQABoAAwDQYJ
KoZIhvcNAQELBQADggEBAJRGdrtyh7IOH3KoHymh83AlVA1KUx97/rD9c3pcS9A1
TSceNqHYDfP+MuwtYhESCEiOGsUI5yxfRda22o5LAZo6N+9Gy4CYgCzeVkCrFfkN
Crr0ZKQjSwVBqgmUI8X493/JzMBpk4MBO3SY3k85mD0ZVOl3xmPgj2CNuTUT0nmA
Ox5N/Ca+KKxBBYqof3F8ZPiHmtVeIOvQzKaUr/E65ihNkslad+eAnuBvvu6OQgFG
HiCO1O8KaHh4YJK0M997uG8pNitbhWbOa0i2iAiXom3MzlajZAxPUWKZd5MOEyAK
pJN7MwMq0zxuLQdqInKcw7AZ8g8LcSOKT9rE1U61v98=
-----END CERTIFICATE REQUEST-----
`)

func promScraperCsrBytes() ([]byte, error) {
	return _promScraperCsr, nil
}

func promScraperCsr() (*asset, error) {
	bytes, err := promScraperCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.csr", size: 895, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _promScraperKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEAprW4lwaQXMrI8UKJGHXtri9bE6RNPwMx2sO/zFWlUYK21yfV
QzT+Y1WbJmEaQ6f4SUYjEdXRTeguyeIa8AoRmH81DdZsO4wFVCi+I7k1TqWxgfAO
9TOPh0m1RRM19FmV1ewOWuShC4sKYy2KgYSHxm6MmrQfa6E3lrRtjOA6FFIitUWv
Li8WXbDUftEU2fmm9kFr+NjWwZHKmeXuPM09Wd3ckJUbD3bFerTlshTYKmOWu4VA
VgNaaR6qgOAPzmwvvwoHScOW642/efaA6eH4HYE6btOF729HqxN+vb9DD3I1G+a5
WZIcCyNmXjArA0HlnhmHj+8O3QAjTmoqUiuF9wIDAQABAoIBAGnKxhIpGzGXij74
HzIDnEo+SQjE6jRDnb6bHDraWufIEKmm4IIevhRhfey0EEvA6yHsvVKTIpjS7+Yz
cy7C5PmmOA/I87QyHiuTE15uKPL42RWBNqzKBJow3zSvhTzEIP65Jz7s+XnuyS+4
9b1NUjBNdTKzfYD6tOERLLgKjzDXDA2nI85tVIqmct5Ye5JnE8UBRFrJgPToNiDP
fC4AZwiZEcDVior5WgckdI9nTNMDAgJY7zlO/JGD+8rDjP4saucOujslf8/z1X+2
r+ghKSgMZ/EfiotxnmOtvu/+oBD7ufQ2fTMxu9F7uL+47UlB6oZgRi8nnum+EH5K
uoFzs9ECgYEAw1aBVP0my1/4UI2ar0fCTV/MBSyP6fvIKgNrOpak8YmkfSppsDEe
iCjMosJKrSOsa6CQ+AJ619IplHjRTSxUrkAx+WA5Qv6Elz6H0FB4pVsZwDK+g5Wo
P4DaMrXQX/qLZqN0woCyTZd7mfqQFgjbAn0nt05LOIiPNFR9uqQgSPkCgYEA2ntE
AgLJFSMQ6shy4xm2cOK8rG89VfFH+W38HU+YdgJXYnPrSycBKggkrFG69nAnVVLQ
xKDhspGJgtflJpmKEjB0ztAzLcvPigVTGnTBUfbLz8+dDaiMTbUofrLDNqzmZP2c
Jr0beKyFxpHLGj1r5JkZxXm8a/kskC4FqzVVcm8CgYBlV673ufLzlpHMsPqsr20W
GXpOwOTVPwSFD4sFNXzTt1Z4fZWhjIpLl+c7FdQKabSdjgtIMHktGWLrHZdxE2vH
j5SdzZdHs6Z0lUN/BxDgsRf2CB2hRPaqI56QqpU2BlVmZa1A7+YRrWK56y3v0J5X
dzkwt9T8upSZULB+MYJyeQKBgGP0Zw3AdnyMGW5AnIcXuWb15LnC/r218GbGEcTb
KHY85fut6uTsCFVRem23yqB6eRRJGigLLpbCjLXmzfiV4BwoPRhtGi0GhIGxo+6D
ofo8vcvqQQEBrobSrZ8ha7w06AcmG+2BMPNJgr5w7wmnNhhUjvzQkAqZ6fBgjclh
UiFTAoGAGkioTa8y1PnT2V68ZF9nEo1HZlCDUxeZjE68ccoHSu6eSH700YiFr1l1
ZDlKvEeK8BmqjzJ86Fnz8k8MoNE4kLCfT5UjoPEPlxtd6OH3zvex0vjvhilMK1gy
Iv/uvS4iHZJr8yaDBSnPfb9De+luFD52x+r/aVvYERzNm43Gy+8=
-----END RSA PRIVATE KEY-----
`)

func promScraperKeyBytes() ([]byte, error) {
	return _promScraperKey, nil
}

func promScraperKey() (*asset, error) {
	bytes, err := promScraperKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "prom-scraper.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIEJDCCAgygAwIBAgIQZF5yeoGfRwAwyYH1G/+pMTANBgkqhkiG9w0BAQsFADAY
MRYwFAYDVQQDEw1sb2dncmVnYXRvckNBMB4XDTE5MDQyMjIyMzM0NloXDTQ0MDQy
MjIyMzM0NFowETEPMA0GA1UEAxMGcm91dGVyMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAsPQLzlCKgISna92hwosWPwImYizAT9FZxbrGhguJhm061s5/
NF3QjlI1mDmhGpmRsyT5cX44AFDZU/hC6eppmmZzbYCWvl3GlGRwg/hf5K6tu/io
VL7DH/6B88GkxvCkpKgI7Uu+Yv3JfAfGZNrhtYsWERD9awpAUZNrLWcFMHrVmqW4
xFdFC4XgBoiL5hzArkS6xnm35h3SEIILgKzCqWgRq01aIvF6daK5iYRF9c2C9pBH
30Bz6EKu7A1H8F4ErjfBzn+JREM+/6bUALUjByEtQDTObMjY7gEJBFe1lJ7O1voE
kVxNGTVlEA6IqcvBulAUofzzMfDBGRK1Rnd/xwIDAQABo3EwbzAOBgNVHQ8BAf8E
BAMCA7gwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBTP
sYp3jHKBRDHLpNBV7OUEJsENyzAfBgNVHSMEGDAWgBR62gAy4CkdFEuOChcak/Vj
CFPerzANBgkqhkiG9w0BAQsFAAOCAgEAOPwS+ECdACPQzOWPnO9MjxzQscgJwHhp
+e18DUfm5fqVCrC8YQYKEFiWwAk55ZwY8nnqhJUNiKcEpWrcWLqnKdeWgGNDdn+x
ktz7r0n/6CTx7qX58C+DZwxY55QoXCxCoo7w+Eb1FC5YVG5SJUdxIWkauFfnxdEx
3OL18w8mN8Hw4zO6MQNqD1XrqBkbQwRrABdWstM03aYwA9mPc+e8Om81vdQJ3aiq
yObbLwJEV5eJdy0XBoum3rn492scYgBv4BP0UtA9s1giUiMz9goZI2pC+M2qb8fY
W1h+RP5GEZelXa3tgTwLDu4YHly0hPz5R31riqG5YaxNwUemVge1VG4lRmz5KPr9
bH2CggvZXtD07ENYipYIbNTmYETPNc6KZ3hNI3yza14gV3778MCx5nFuMUoAeNd4
YPQy6w7zVuQOvvq4DG98dNMsD8uaAPRc5CqkAilUdo371qlzTDgAoZK8s6XampxX
eBPna8rhA/BavI4sdCUcmTPls7EiwtxdEr4BnBfYAW1etv8JQE1Vl8ifLg6/YjkY
p8YQzJIHZb2YGltjYkK+mpLoxa/hxtzhgmPHYRRq6NgNsFS0mqIORhipYNChJ9Mm
h9xAd7ytMrpcYBAA34xcoClo0hW7t5bM7cFmzQjnNfC7RL1+JyOJV+GiU9Vh53V6
WYmpBfKDGxs=
-----END CERTIFICATE-----
`)

func routerCrtBytes() ([]byte, error) {
	return _routerCrt, nil
}

func routerCrt() (*asset, error) {
	bytes, err := routerCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.crt", size: 1497, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAxMGcm91dGVyMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAsPQLzlCKgISna92hwosWPwImYizAT9FZxbrGhguJhm06
1s5/NF3QjlI1mDmhGpmRsyT5cX44AFDZU/hC6eppmmZzbYCWvl3GlGRwg/hf5K6t
u/ioVL7DH/6B88GkxvCkpKgI7Uu+Yv3JfAfGZNrhtYsWERD9awpAUZNrLWcFMHrV
mqW4xFdFC4XgBoiL5hzArkS6xnm35h3SEIILgKzCqWgRq01aIvF6daK5iYRF9c2C
9pBH30Bz6EKu7A1H8F4ErjfBzn+JREM+/6bUALUjByEtQDTObMjY7gEJBFe1lJ7O
1voEkVxNGTVlEA6IqcvBulAUofzzMfDBGRK1Rnd/xwIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAD9WUceXKLQZNICXukBiZIlT0Ey21O+Pwi5aVYk+GrFAv7dc5t/W
tvuu9WdkA2wtmP2zj7uI1N5b/W+mVjtpoSdslZITLiq97uzdLpR/ZMYDGcvaQCz7
tjfHKhl9iaTxzVO5F268q89+NCR3dAEneB/RlnYuXd+jKq65l/DJGs1nCcOeNW33
3pV3nf/yGXRHMhIeS/bsAwyb6N7upxdfxrALy5UPZuHcr6fzka6WqBgSNs26v8TE
9FIEJIPBIhUQTjy0eqDTP500HnSEg3EKxbLK7vbJbC4egGTApCG0WmTOr0ule0Yc
EOBAjPSgwfy2m14LBfkswaDjiQW06PRGsZY=
-----END CERTIFICATE REQUEST-----
`)

func routerCsrBytes() ([]byte, error) {
	return _routerCsr, nil
}

func routerCsr() (*asset, error) {
	bytes, err := routerCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.csr", size: 887, mode: os.FileMode(292), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _routerKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAsPQLzlCKgISna92hwosWPwImYizAT9FZxbrGhguJhm061s5/
NF3QjlI1mDmhGpmRsyT5cX44AFDZU/hC6eppmmZzbYCWvl3GlGRwg/hf5K6tu/io
VL7DH/6B88GkxvCkpKgI7Uu+Yv3JfAfGZNrhtYsWERD9awpAUZNrLWcFMHrVmqW4
xFdFC4XgBoiL5hzArkS6xnm35h3SEIILgKzCqWgRq01aIvF6daK5iYRF9c2C9pBH
30Bz6EKu7A1H8F4ErjfBzn+JREM+/6bUALUjByEtQDTObMjY7gEJBFe1lJ7O1voE
kVxNGTVlEA6IqcvBulAUofzzMfDBGRK1Rnd/xwIDAQABAoIBAGBAXyuaI7xEa80A
gTyQ60jaooZEUVcZSPuE3PeMzwGP6LFvIUIaxZakoQJsVnVhkx8evZA+V7fUQmKq
Z7tVBpw1nhOyHkzuNVYCTDF8qKx7V4UnfGicWwbMKWOtsTOFMgleXXy19plh8nbE
w+WYKa3WOeqOk0nmCZZV2baYkvoK7so4mERIm1rGaQ6oi1LUhhyII6fUpp3AV4Vx
KKmUL+YvrERZCb03EumvLaKYmFKVCgvNhsl0gvLbsKuW49l2X0R0dhRlUwHunXhx
sfHeGYNqKuLKswxVmUDAt2/UDpbl523IUfTh1EIpGIiwZ18ZjOIBR/tbPRQKDqQo
xj/t8gECgYEAyhN4H0sMBB17gi1dwv61c7NA1upYkMfgi+CiQIdMOxLjsVlO0ypP
ORDBeUllkBH+UkXDG+B529jr4Et7vI0ZIVWwBcrshGmcHZIchRNdKILrP6yKebHM
rFBsBP8Ru4xzIR6gr/uFgaLHpMcv6cnl9d47yb9xxj4YxuYCyE+hHxsCgYEA4Cxa
ZKRCwOfSuhPew2wAK4lj8jkGZFferC2Dim/6UHnLe4XkOoRZD/sn3NkfqoyeRDfB
jFjkYRWNtGChD2gi7fQx09mNriqcyzOFaGjcuQMJA4t3nhoPqtivRO+W4OefDS00
kFqjQNzwi/3jymz9YUNjgK7QoVpIyoc7SJfIsMUCgYBHV+xXEAXkBgyu/xlVWNvz
R1wjBIXUR90tRVfDdIEjch3VZXSA9TUXLqVADvu+i7vAjETAONaNGd7dR4keHqq6
rCgDQ4uRjD/D6OwMx7NiNCaeSmpxYKakR5h7gxpdns6e6NNOjnyqMjBOKsztu4xm
69kr911R4maZAmgFFKgL9QKBgQCVmuQEkF8AUHYguswKzVPbukgaShZK9x1i+Mj1
pb9+35l96SAkMVkiwjGbQMfSUR/6VN91Y4mehPzZ6TbzikLtXO+3+1ODbWrQbaTV
xk2vpyfn1rbQq4HTOeLWdbLSi6Fo8MdIo0SaMBjUxG62FECRHaEVKxWO6Sr1BoT4
8Fr+JQKBgQCXjPDCb50sdLW53H6btgl/1vv4RbS+5peKrWhkNH0lnRfCcJUU/0tf
y1VsS2lnvEml/RBRVfkrmhX9JSIUNJ/bZccFtAcK7O9HsAtoIjdq95PyF774lQ22
4feMM3GSMAjm68egj6iIY8eHnL+SHeJtCohwrmqLlyj+GK/Ta+M2uQ==
-----END RSA PRIVATE KEY-----
`)

func routerKeyBytes() ([]byte, error) {
	return _routerKey, nil
}

func routerKey() (*asset, error) {
	bytes, err := routerKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "router.key", size: 1679, mode: os.FileMode(288), modTime: time.Unix(1555972426, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _syslogAgentCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIELDCCAhSgAwIBAgIRAKFBoq/kRrWiHMtX6d6d4ikwDQYJKoZIhvcNAQELBQAw
GTEXMBUGA1UEAxMOYmluZGluZ0NhY2hlQ0EwHhcNMTkwNDIyMjIzMzUyWhcNNDQw
NDIyMjIzMzQ4WjAXMRUwEwYDVQQDEwxzeXNsb2ctYWdlbnQwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCsPnMk5Mm4WJq27PPPHDS6tbTZSNkr2T85fdxt
XiCq1Rf+uXU/wB6yGF/EB/kMKnICVOvhT+zJKd+Y0tNovAXDV2vnY0SUjL6YjWfC
8DXbkvzMVV6F8VYJskDbef9oXDEiWeCPf8rIJB7XsB0pNg8bi7QNazIAMbnWF6l2
C50eg+iK81PQPOqUaiCa9Dx/OLH13jKeqB8fY+xgY7DuQGoZ2GS3aeqb+MC74xfV
5vkafRaWMzK5m9/5zMm7rh63093qHu8tVfvxA4PFOklX9MFfDjkcROJzwQnYnGV+
VcHJw8I6bbfUXoTmCPVNcbkdAGrPDXiHA0qE1hPXrO/3tGCVAgMBAAGjcTBvMA4G
A1UdDwEB/wQEAwIDuDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYD
VR0OBBYEFIlAGoaveVMBexf9JbmhifHkGYX1MB8GA1UdIwQYMBaAFO8+YYjqHJbI
kBGrNRutV3CV5YfTMA0GCSqGSIb3DQEBCwUAA4ICAQBTmM7S2t7rMQyecC4Bj8uf
f4SCXRae8BfKBxUVDdWJJGkjs1E89bGo+qtqKBJywhmG8Bs0M1FOXnu2/ph2uMWV
nZ2b5NtxeEHKwHaMPHKx7+ezdlphbgMWPrhQqCpJ9tITNGbCZ1vDOi4eh1ewV/ue
JFOX8yKwdGhGIF1drApdJ6OWucCYUxOeV2MIwHFRt9ng7ps937SYuTwnbhcTpsRU
u66lwR5CLb4VkscdgssmPe8xAydK5dyBNk2mCTCSDBcDl4Fy22PG5Ls1TvEBCP11
gpPzvGziXicdwSlznvN4vgen/20FxVbMsNCrQiWjgr6LnflnuPT5NcyckfjZfU5w
bjqZKvMSmwQOXAuojQuXtwIndNG7Pe9IJyAjGRk6Kan5BMyd/ZA/4BhUYLIyN6WG
iXmeOPAWRrpCr3YTPFkt9BB656dZSBfmMBMg4S0k9DbrIxbSUluqJ4ivujW9Mqep
i5HN+cI0C5D15OKYeKb2NpYe8dajig0qAJH0htIQ5cb+MPWj7w6DnKT/yljl6xjk
tHdveAscr1rm78yj8qnQhRC9blQihh2A8RmmiD7Mvk76ZGVg8qwVH4X4fo6I7ksi
nRgjSSbDT76qSnConQ2DFhKi98TIeSdPaqvrxaFiW4Gc2NlPWtg0eQvDnVm7KThG
do/AQk4FDG686WrRZgWOAQ==
-----END CERTIFICATE-----
`)

func syslogAgentCrtBytes() ([]byte, error) {
	return _syslogAgentCrt, nil
}

func syslogAgentCrt() (*asset, error) {
	bytes, err := syslogAgentCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "syslog-agent.crt", size: 1509, mode: os.FileMode(292), modTime: time.Unix(1555972432, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _syslogAgentCsr = []byte(`-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAxMMc3lzbG9nLWFnZW50MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEArD5zJOTJuFiatuzzzxw0urW02UjZK9k/OX3c
bV4gqtUX/rl1P8AeshhfxAf5DCpyAlTr4U/sySnfmNLTaLwFw1dr52NElIy+mI1n
wvA125L8zFVehfFWCbJA23n/aFwxIlngj3/KyCQe17AdKTYPG4u0DWsyADG51hep
dgudHoPoivNT0DzqlGogmvQ8fzix9d4ynqgfH2PsYGOw7kBqGdhkt2nqm/jAu+MX
1eb5Gn0WljMyuZvf+czJu64et9Pd6h7vLVX78QODxTpJV/TBXw45HETic8EJ2Jxl
flXBycPCOm231F6E5gj1TXG5HQBqzw14hwNKhNYT16zv97RglQIDAQABoAAwDQYJ
KoZIhvcNAQELBQADggEBAAOxtbgJrKILmfWrw+T0x2xHaphk9esZW4uJ5q+RGRBy
8E0+dg8/kRhW/HkpFhNGeCOvTsecGEkwNIAYWo6fzfddXzEMU6rzT8gPbqFNOlC6
T3MlYvhwmiClrlzhjI/bo+RKS/ZI1s6efeLtF5gaCfYMqGTVOczTtv2asR/Ypgod
uY7KAzQGS2NA6cXH6HD708BkO6Radwhu1OYz0afca8eNAeR9TgZ5YwFIaqoiJiT+
tZeZPVSOAJgD8M/aqR2EOLUNSsDjCVXc0+ti3Bl3SfAhHNC3GJvLBwTk2EQLjCRK
3UvPtAma33pcmRV7X51DVyZ7nUmOSrApJBsrmwiPGG0=
-----END CERTIFICATE REQUEST-----
`)

func syslogAgentCsrBytes() ([]byte, error) {
	return _syslogAgentCsr, nil
}

func syslogAgentCsr() (*asset, error) {
	bytes, err := syslogAgentCsrBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "syslog-agent.csr", size: 895, mode: os.FileMode(292), modTime: time.Unix(1555972432, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _syslogAgentKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEArD5zJOTJuFiatuzzzxw0urW02UjZK9k/OX3cbV4gqtUX/rl1
P8AeshhfxAf5DCpyAlTr4U/sySnfmNLTaLwFw1dr52NElIy+mI1nwvA125L8zFVe
hfFWCbJA23n/aFwxIlngj3/KyCQe17AdKTYPG4u0DWsyADG51hepdgudHoPoivNT
0DzqlGogmvQ8fzix9d4ynqgfH2PsYGOw7kBqGdhkt2nqm/jAu+MX1eb5Gn0WljMy
uZvf+czJu64et9Pd6h7vLVX78QODxTpJV/TBXw45HETic8EJ2JxlflXBycPCOm23
1F6E5gj1TXG5HQBqzw14hwNKhNYT16zv97RglQIDAQABAoIBAA/ab56lsCtXfGX5
yTb20aOdtdeJ7PMsO7V+8Brg3wDaPCslxrTnaevacnYIhdOo1HWCe3Nxd8nMINhg
DzVEmQMxuKzDZjyF98TyvuoiUdKz5LCp6tlJLTIXRgDtaaShV6RhwVlz2aYyLOSN
QSHZ5+oRIbFafG+oJAKgiuhiiUOVmdkZoDTTTOgo/Tlj+cdbQJAOnjS5uV/JdCCb
ZRt+ixKn9HbTtTlAXbDg64a57XLkAdawnsFoIK/rwMAzoPMi/Cbb4UJYOOG4IHkq
mQoHLJVHziNy+v4t6T9SwaaDwuBQHcVzXKBsUEuqwWxl5Z60ld6KKk4ME/0Ho/7f
YCOYwMECgYEAzxSyyyNPcbMPgK82Bi7LEi2ynx/0oKydAVrKWPLkgVilkUSCU5nz
PXqlJZA0GpRkIyfrGJ3BpkgWBtv1TXT5RacvLpGaNEcswGhq/WRTu7mLndYNm2nX
lINDaZ/dzNa31Nk4YsjBeyey3seST99+lCCycZZntCNJibJ77EkTt5sCgYEA1O75
hKq93ZJVpJK8uDW7YNRthGn+RQFBqLo+ycThZwGUTmhfRPj068ZkzfVXBV1K/+Dv
mFM99MTg1WE70wLbTdPpS+NPVddKyWtHZOFJJQh26uyI1DsatqObfSxUP3ixBDsi
OxS9mgqZb9pxUfUYZHgHzujeDCX6gFy65wk+A48CgYA2MWWFEe2VhNXWyIOr5I0S
adEoIZXEgsfn9dmko5Q3YXqa5MHynQRyH2mexflMx27ZYHX/EDIAkTbqfp/YsHcX
ymPnnQUtDz9f7zOospvTMgCewsj21iEr5Zo7xzGljL+5PUurVnyD/WSrNrFMo+Gd
ZF0uqrzjAKUbGxGhSZKWZwKBgGSTF8IlD5cXZmJceM0dfArpa20uz03yoPu8NKoC
12Ba65z5SX5/hNfUlop9hoPfI+ymZyTwtIPndjbzPVmWsNUa8cfJbxChpw5qIIey
rWTTka+2144++Igp0OiXxpdQP3Q7Jhj32/JlbUHa0MmgVcwmsbF2ZmMgkSiOJC26
PNNbAoGBAMlUgVWoGUNDOH0NYDYicrdp0TlBn4X7fpANuaq9equrIduNrspBVE8t
hhvBlhjMzGTHiautdMBB8vS723Gi49ZL9BdQjcX8c5fHFFJ44emZnoXOCFMZkoDP
Eg9AlhP/uD62IsQe1XhSsJxmEw7mlIXBH7Sg4ptMOnKZ1Z5eRofN
-----END RSA PRIVATE KEY-----
`)

func syslogAgentKeyBytes() ([]byte, error) {
	return _syslogAgentKey, nil
}

func syslogAgentKey() (*asset, error) {
	bytes, err := syslogAgentKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "syslog-agent.key", size: 1675, mode: os.FileMode(288), modTime: time.Unix(1555972432, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _systemMetricsAgentCaCrl = []byte(`-----BEGIN X509 CRL-----
MIICiTBzAgEBMA0GCSqGSIb3DQEBCwUAMBoxGDAWBgNVBAMTD3N5c3RlbU1ldHJp
Y3NDQRcNMTkwNDIyMjIzMzU1WhcNNDQwNDIyMjIzMzUyWjAAoCMwITAfBgNVHSME
GDAWgBRVWxhImk6s2+LYWDh+5BesD79R7TANBgkqhkiG9w0BAQsFAAOCAgEAyEts
Sr1+3haYUJaejFIzbfjpGJIVtLJwO+o7ZcLAYrAcLTQs3clvEgTo2uw1nd9CMDyl
K6RLLD8jk1/0nzz3Gt0G+P3LT3g+iEYRn2MgTOuqB/dOmlKi639ttx9gBjj1Cx2W
CTgRWqYrmFnlM42Ls+mESPW0hv1s4Z/nTAIAshwqHfyBC/sZSpAuIE+49jaYN1Lu
gKcUidEJDn88Yh6nFOB6chHY5ohUxop4HeU0GYGNhqgPvIuHWK5fhL64rlM7SCOt
K3eYpP8jAGmGoIy+XUwWw5kuCMlSsPj71XHfHOOVZsmW059RkWyBi+gPONie8ye7
LQiK7TsOE9WHOz2d9YgETC0w2ZM96KiCyISDQPNyV4Fa8+JFjDhVqp5OORPQWcM4
b0lExwmupkarf7ISeAPdN+ysjtDHwgLqssGbLkjjUQqq84XbsXawVAr6nbqH1ysJ
rhWrtLbCgpRmrC3RRRCy05v3QPJhj5wGdGYi9Lqb4OFwqxXNDNBl4cHVpj6XO9iR
xEOlHww9CzGQPijA6DFM9Om1Hz3cyasPQe1GHo0SSOwt/paXkplpiAW6C8pJYqXw
z3mjpXLnfDRO4zHgL4n0kDKtI+MQzeHZHpnSliBsaQxLZbVxcihYwdL+wxgpiC1G
DFt1jKOURc2QT89SkwX7lCs0PVgZ8ix7QNP5GmA=
-----END X509 CRL-----
`)

func systemMetricsAgentCaCrlBytes() ([]byte, error) {
	return _systemMetricsAgentCaCrl, nil
}

func systemMetricsAgentCaCrl() (*asset, error) {
	bytes, err := systemMetricsAgentCaCrlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "system-metrics-agent-ca.crl", size: 934, mode: os.FileMode(292), modTime: time.Unix(1555972435, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _systemMetricsAgentCaCrt = []byte(`-----BEGIN CERTIFICATE-----
MIIE9DCCAtygAwIBAgIBATANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQDEw9zeXN0
ZW1NZXRyaWNzQ0EwHhcNMTkwNDIyMjIzMzUyWhcNNDQwNDIyMjIzMzUyWjAaMRgw
FgYDVQQDEw9zeXN0ZW1NZXRyaWNzQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAw
ggIKAoICAQDnyH/uBZa7VLB2/UjdFEznIMAU9tuG9KhWykroweglHaRhU0wyz27v
iso0Lj2wKUDr9HRT5c4bqcUFjNXS0JOo6KlIP5Mkmy1r8NHUWDqxPBZJ4lV3rtF8
IH4Iiyi1pa8+o3M+E9RuSpof8KogbPizWY/GooDo6l7awa+uzvALKlEmVQYLfvTL
SEKRUblIOPD4WfkdmihVGoqnwv3CszLTDS4fXORykUdzxJ1UkvtMqx+BRQKtyMrJ
OIVlbWEuxkFBwS8hM9Y2ed4/Q87C67rtH/5XaDJG5w9WVdu43JSOR7K6tzqzZO7o
gUYJHKZuB3XnIIvlsIml/O16yCOiXKHRtEjkjaQ1KfihYQLR5iPXU3JJssvhAM5J
p271mfFEvw2WxKhzvJ7mw068WENxETnzYCmPmZdzKt3r7KucvqoD30LgKm+SkRPN
x2+u7+rvW40V+Lw0CM4jw2Du+huqKsRukZDEarVETiqSqjPjZkhDYE0LtNXXVhrX
3tCDTa1MEjwr+hPqT/NujE1lsI5TUyeJjWY00FKCRzI9/tgxgN06wUyIwys1xlGu
QGcU7T7y7c/+pS0h3qTBaQk/eUZBBrJRQt+I+UjGvBFLIhW8PKhgK3/jKM6lPcuz
sfEWh81MczwHGo8QlH8sFNtGMp+MECKjL7iTv/mdbUGZwOSyMmUNXQIDAQABo0Uw
QzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU
VVsYSJpOrNvi2Fg4fuQXrA+/Ue0wDQYJKoZIhvcNAQELBQADggIBADrI+fI8IcDq
FqldiLkbRN0ETLaQxRZwZVFVW/y3O+v2qWozDqz4u3ykMKKmHlV719jvuXvcrg4C
3KKGfLyjs4iRPgEuntJC6zO4f8aYwtnH4ddOOaZfoiKq+/X7UUd5TmYgVgdeoXqV
dQ00MUE+/OKkhuVA7Bjr7jjFu87O2T/a6PQtPq1NKe/tsrM8tDmFyOWXTr48wufc
0yoQTxxLJwUhW7YTdqq53gYuqlWLadtbYmdM3vMWZiV+iHiX9ZVnhGuWQXI5eyty
J1e+slyyIJiPVlSaHtLIBUiliCZylls+vUIAEhvrMyLD+V2iZT3kTVnlLDVuKZN5
gx6gdhN6i0efhMn1oLmdh9MzgNohQbA+vLNNZmH1jhbCXrpS59c2hs3z56y14aMc
owW2DXVu6+syRu0s9aRFSOtzbePNGxTKNEaOhx66AoUNJd5KByytQvcP+MKEwS1y
eKByCpjmkNIYenZjm+3wZPo1AF+3EBU99Ln791aKb94eTX8rcK8cw5uT2W3jCNbU
7miInYquWd3tQD/MdwmTjo+cs/neBeKIrX6OPGfzEqKWFfUvpNDEqvbagq5UDERN
BY4VMytd/L4wxkO+F4Cn4XyEGLSlwWG18ZPaHlzSY9kUJgcZOarWQt2ZheHd5ET3
zr9KxlB6M1gfdYxKcjqYDX6jE6O7T+v6
-----END CERTIFICATE-----
`)

func systemMetricsAgentCaCrtBytes() ([]byte, error) {
	return _systemMetricsAgentCaCrt, nil
}

func systemMetricsAgentCaCrt() (*asset, error) {
	bytes, err := systemMetricsAgentCaCrtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "system-metrics-agent-ca.crt", size: 1777, mode: os.FileMode(292), modTime: time.Unix(1555972435, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _systemMetricsAgentCaKey = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIJKgIBAAKCAgEA58h/7gWWu1Swdv1I3RRM5yDAFPbbhvSoVspK6MHoJR2kYVNM
Ms9u74rKNC49sClA6/R0U+XOG6nFBYzV0tCTqOipSD+TJJsta/DR1Fg6sTwWSeJV
d67RfCB+CIsotaWvPqNzPhPUbkqaH/CqIGz4s1mPxqKA6Ope2sGvrs7wCypRJlUG
C370y0hCkVG5SDjw+Fn5HZooVRqKp8L9wrMy0w0uH1zkcpFHc8SdVJL7TKsfgUUC
rcjKyTiFZW1hLsZBQcEvITPWNnneP0POwuu67R/+V2gyRucPVlXbuNyUjkeyurc6
s2Tu6IFGCRymbgd15yCL5bCJpfztesgjolyh0bRI5I2kNSn4oWEC0eYj11NySbLL
4QDOSadu9ZnxRL8NlsSoc7ye5sNOvFhDcRE582Apj5mXcyrd6+yrnL6qA99C4Cpv
kpETzcdvru/q71uNFfi8NAjOI8Ng7vobqirEbpGQxGq1RE4qkqoz42ZIQ2BNC7TV
11Ya197Qg02tTBI8K/oT6k/zboxNZbCOU1MniY1mNNBSgkcyPf7YMYDdOsFMiMMr
NcZRrkBnFO0+8u3P/qUtId6kwWkJP3lGQQayUULfiPlIxrwRSyIVvDyoYCt/4yjO
pT3Ls7HxFofNTHM8BxqPEJR/LBTbRjKfjBAioy+4k7/5nW1BmcDksjJlDV0CAwEA
AQKCAgEAmO7YSkrxu8UTck+JBiZg35fiZXLEQnWnpSxw5Mccz3CRh44YluX7gp6G
8IsaNOPjbEytfLYCmooX76OPajwpUafCGmOoSN0CyVfqezuD7nGBG1r1nbSBkG83
+ZcoU0JxMNlULr+SyPr8WtrGxgJgzqXnkd6jRAtwbtKhgqwUAqn3RV2QUYGBL6gM
FCpiIF9Bz/w9vOR8fDq5BhxIp3DptgvaRONb8KQfCynNzYH1wg6fCQJp1BTKiJ58
lgHnv58ca7B10miLjQI4PHIXONGlUtRrU2zyz4mhuwuHoKAafQ6dxUkkuD1+zXaO
qXB3992AU/JLnFAxYo5Se1MXAAgy1BNUq2GwqLR5NiI4lVFlIMPcX65vF2J6V7BC
sKvNiUUjjd3G6H/da0rafJQRwLwzNpr5YbR+xYaP44Zu6H5oDy/lny5UE5VbwMY3
vzbKRu2LolQzK/EgPmXi2HKkBfCN+eWmQf+zEz8OZeaHh+RfXwmF/6l8x18Qli9q
ZRNK4XWJR2cYTjpuWNRnBO9WLYxhez6YMfT+aSjalADUyAWVecf3fhGtQZ+SNQ/X
1JASW2yw12jNG8NNtqvCRCAZ7XsZ/Pkc4bYbiP3ptgJcgfsV+leJrD+D0sVDw5y0
lOwAbi+CyQgSnaXNa0bhCVhnmkH2URTuRXqBkNqoWnXlpaWFgQECggEBAOf8nw/7
B9n2PxictlGDfmHkIk6KeupSopNHzqRmMftGEDZsWtHXzMkUzsf6BhI4na7G1ARE
wTZJonJnQZK24TWZBpKJMkGub5ANQKsjgMty8VPA7DUGPfj6jzdCEt5gmf2fBJik
IkKkOIPcSw07HMYOV21/MRGoH3tVQjY2gduyXKr3vxGTfRVtmZkhSiZl9vQ4fKxF
zIUh24QblSUmf8HPl6EqEWnuwIaXbjhyBJUrVORDwWHv/ny0MuEIj/p2+gKV+K86
k3LqSH/seB1CfUavC0+UnNg1qMrE1BCUwl7xpzWzJpQlI9kfxOU570MY9py5JO7b
O7/TTy5UhuBojn0CggEBAP/Ge7Slq4ALyxvT28v6MOTI33HnHgSqOD/jj9+dHJOP
htT24Idg6ZigrovJFmu8QOBhS8mbbiNK+JsuO58I2l2q2ZsBqCkhxU9z7BrIy5Hf
9eBH7BkwFWZdhwDItAgPUr0r5jgTsl28AcSagJvJsypuM100eSIHTBvR/mKRS8R/
590Z40MJVePCRXb4i5rOVrinTfMZeRSm5N5nczL2WjTeXTFUcWatPB7T4DQaN0bM
WfCgCNSlvHYi6vpQb/SQ7CAC7l3kevVmyGb34MXTeNe+dNUkL4jX7cvzZ47bpppd
Yw/mmIB4Pgi47zUqfWEWBHUp+QlRjy22uVBQ2YtAUGECggEAHRCukR7/fdR3VUsV
IKNb60Hc9oAtJDyUN+WwQzK2omfF0jvDKTVjZ/IecjmmFxRW1TX+DEbc+kNBghnj
wlD9aGyywRtFW6tSOPcgGhEJqvPMvpSWQ5Jzo0UpOmAh4xCxWnBY8BLoY/cVSZgJ
IzA7y6iyVXqxGCg7QYWOFSLBJFh1ecouezJCYrPnoaLlGmh+B10oaaEZHbj/Os8F
4bCwIwUyVzPhGKecIYDJg3Ltlg7mxO6kRPP/q3ocQcuD1nqfmkFV9gZdwPEPgk+L
QQc6kOePgDn7aK9YZYdBlo48yA54x6aZd8grdKGhVqLqkjqHc11S/kYjd0YvTnuy
pl0TNQKCAQEAnsCuJXiykr4/KZ18jgVS9Z2r+oGNwy13zkfLE+rrQrdR47r7r2s6
ce5BiCeej+3/goVBSff8C1HMLl0qylHvXzXc7HXBzw3T7rWvtQwuNfOBI9zgMN4E
Wk3wrk7kVyBTpXCq6uFm0wEPQ9z1uDwfxVUy8kXQbYuD9LyJHNq74VHWMwiPYxtX
QQ9imC46UDKD5waIvjtwSJ4x7czd1qLLaIcf5q9X13fsmeG+BfjDmGDb7hsWgA4C
hHy1xfnJE04kENZg5swaeVh7SFXQIFlaZuYik+xqyI/lW7JO839nz+Xox4TD4PFA
558JccFWorzMtYAAv4Tszl3cdXpJHEIl4QKCAQEAjsxM9qQMPyeH+q8DweS5kDt0
EtyrOaeF6qZD2Fmrkk+3pqGNhJqiOhFa/BqiGAeem6Jq0yI/b18b9PAg1SI5J4nh
OPbTwD63BMTY7tAtuRmiVHkuqdoilSuZhad2WTxdtD4jHKBSUlY6kpWcKgC4U2Zn
n1i1MCJxfUib4bXc5qiKLimmyASSNeRVggseWaf4XhOKQhW4NuycMQeSFgJB3SKy
zTnFm7WNPd1YSnzqu76fHJPmiO161A9u89E89qTwWG6ue6cobaJHPiKewWUlSPco
WfO51g1TeyuIS1epieEbHBUWEmtKOo94taIB7MCi5NH4bwrHVj2iGD0z88gm3Q==
-----END RSA PRIVATE KEY-----
`)

func systemMetricsAgentCaKeyBytes() ([]byte, error) {
	return _systemMetricsAgentCaKey, nil
}

func systemMetricsAgentCaKey() (*asset, error) {
	bytes, err := systemMetricsAgentCaKeyBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "system-metrics-agent-ca.key", size: 3247, mode: os.FileMode(288), modTime: time.Unix(1555972435, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"binding-cache-ca.crl": bindingCacheCaCrl,
	"binding-cache-ca.crt": bindingCacheCaCrt,
	"binding-cache-ca.key": bindingCacheCaKey,
	"capi-ca.crl": capiCaCrl,
	"capi-ca.crt": capiCaCrt,
	"capi-ca.key": capiCaKey,
	"doppler.crt": dopplerCrt,
	"doppler.csr": dopplerCsr,
	"doppler.key": dopplerKey,
	"forwarder.crt": forwarderCrt,
	"forwarder.csr": forwarderCsr,
	"forwarder.key": forwarderKey,
	"loggregator-ca.crl": loggregatorCaCrl,
	"loggregator-ca.crt": loggregatorCaCrt,
	"loggregator-ca.key": loggregatorCaKey,
	"metrics-scraper.crt": metricsScraperCrt,
	"metrics-scraper.csr": metricsScraperCsr,
	"metrics-scraper.key": metricsScraperKey,
	"metron.crt": metronCrt,
	"metron.csr": metronCsr,
	"metron.key": metronKey,
	"prom-scraper.crt": promScraperCrt,
	"prom-scraper.csr": promScraperCsr,
	"prom-scraper.key": promScraperKey,
	"router.crt": routerCrt,
	"router.csr": routerCsr,
	"router.key": routerKey,
	"syslog-agent.crt": syslogAgentCrt,
	"syslog-agent.csr": syslogAgentCsr,
	"syslog-agent.key": syslogAgentKey,
	"system-metrics-agent-ca.crl": systemMetricsAgentCaCrl,
	"system-metrics-agent-ca.crt": systemMetricsAgentCaCrt,
	"system-metrics-agent-ca.key": systemMetricsAgentCaKey,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"binding-cache-ca.crl": &bintree{bindingCacheCaCrl, map[string]*bintree{}},
	"binding-cache-ca.crt": &bintree{bindingCacheCaCrt, map[string]*bintree{}},
	"binding-cache-ca.key": &bintree{bindingCacheCaKey, map[string]*bintree{}},
	"capi-ca.crl": &bintree{capiCaCrl, map[string]*bintree{}},
	"capi-ca.crt": &bintree{capiCaCrt, map[string]*bintree{}},
	"capi-ca.key": &bintree{capiCaKey, map[string]*bintree{}},
	"doppler.crt": &bintree{dopplerCrt, map[string]*bintree{}},
	"doppler.csr": &bintree{dopplerCsr, map[string]*bintree{}},
	"doppler.key": &bintree{dopplerKey, map[string]*bintree{}},
	"forwarder.crt": &bintree{forwarderCrt, map[string]*bintree{}},
	"forwarder.csr": &bintree{forwarderCsr, map[string]*bintree{}},
	"forwarder.key": &bintree{forwarderKey, map[string]*bintree{}},
	"loggregator-ca.crl": &bintree{loggregatorCaCrl, map[string]*bintree{}},
	"loggregator-ca.crt": &bintree{loggregatorCaCrt, map[string]*bintree{}},
	"loggregator-ca.key": &bintree{loggregatorCaKey, map[string]*bintree{}},
	"metrics-scraper.crt": &bintree{metricsScraperCrt, map[string]*bintree{}},
	"metrics-scraper.csr": &bintree{metricsScraperCsr, map[string]*bintree{}},
	"metrics-scraper.key": &bintree{metricsScraperKey, map[string]*bintree{}},
	"metron.crt": &bintree{metronCrt, map[string]*bintree{}},
	"metron.csr": &bintree{metronCsr, map[string]*bintree{}},
	"metron.key": &bintree{metronKey, map[string]*bintree{}},
	"prom-scraper.crt": &bintree{promScraperCrt, map[string]*bintree{}},
	"prom-scraper.csr": &bintree{promScraperCsr, map[string]*bintree{}},
	"prom-scraper.key": &bintree{promScraperKey, map[string]*bintree{}},
	"router.crt": &bintree{routerCrt, map[string]*bintree{}},
	"router.csr": &bintree{routerCsr, map[string]*bintree{}},
	"router.key": &bintree{routerKey, map[string]*bintree{}},
	"syslog-agent.crt": &bintree{syslogAgentCrt, map[string]*bintree{}},
	"syslog-agent.csr": &bintree{syslogAgentCsr, map[string]*bintree{}},
	"syslog-agent.key": &bintree{syslogAgentKey, map[string]*bintree{}},
	"system-metrics-agent-ca.crl": &bintree{systemMetricsAgentCaCrl, map[string]*bintree{}},
	"system-metrics-agent-ca.crt": &bintree{systemMetricsAgentCaCrt, map[string]*bintree{}},
	"system-metrics-agent-ca.key": &bintree{systemMetricsAgentCaKey, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

