// Code generated by counterfeiter. DO NOT EDIT.
package cachefakes

import (
	"sync"

	"code.cloudfoundry.org/loggregator-agent-release/src/pkg/cache"
	"code.cloudfoundry.org/loggregator-agent-release/src/pkg/metricbinding"
)

type FakeAggregateMetricGetter struct {
	GetStub        func() metricbinding.OtelExporterConfig
	getMutex       sync.RWMutex
	getArgsForCall []struct {
	}
	getReturns struct {
		result1 metricbinding.OtelExporterConfig
	}
	getReturnsOnCall map[int]struct {
		result1 metricbinding.OtelExporterConfig
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAggregateMetricGetter) Get() metricbinding.OtelExporterConfig {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
	}{})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAggregateMetricGetter) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeAggregateMetricGetter) GetCalls(stub func() metricbinding.OtelExporterConfig) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeAggregateMetricGetter) GetReturns(result1 metricbinding.OtelExporterConfig) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 metricbinding.OtelExporterConfig
	}{result1}
}

func (fake *FakeAggregateMetricGetter) GetReturnsOnCall(i int, result1 metricbinding.OtelExporterConfig) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 metricbinding.OtelExporterConfig
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 metricbinding.OtelExporterConfig
	}{result1}
}

func (fake *FakeAggregateMetricGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAggregateMetricGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cache.AggregateMetricGetter = new(FakeAggregateMetricGetter)
