// Code generated by counterfeiter. DO NOT EDIT.
package cachefakes

import (
	"sync"

	"code.cloudfoundry.org/loggregator-agent-release/src/pkg/binding"
	"code.cloudfoundry.org/loggregator-agent-release/src/pkg/cache"
)

type FakeAggregateGetter struct {
	GetStub        func() []binding.Binding
	getMutex       sync.RWMutex
	getArgsForCall []struct {
	}
	getReturns struct {
		result1 []binding.Binding
	}
	getReturnsOnCall map[int]struct {
		result1 []binding.Binding
	}
	LegacyGetStub        func() []binding.LegacyBinding
	legacyGetMutex       sync.RWMutex
	legacyGetArgsForCall []struct {
	}
	legacyGetReturns struct {
		result1 []binding.LegacyBinding
	}
	legacyGetReturnsOnCall map[int]struct {
		result1 []binding.LegacyBinding
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAggregateGetter) Get() []binding.Binding {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
	}{})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAggregateGetter) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeAggregateGetter) GetCalls(stub func() []binding.Binding) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *FakeAggregateGetter) GetReturns(result1 []binding.Binding) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 []binding.Binding
	}{result1}
}

func (fake *FakeAggregateGetter) GetReturnsOnCall(i int, result1 []binding.Binding) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 []binding.Binding
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 []binding.Binding
	}{result1}
}

func (fake *FakeAggregateGetter) LegacyGet() []binding.LegacyBinding {
	fake.legacyGetMutex.Lock()
	ret, specificReturn := fake.legacyGetReturnsOnCall[len(fake.legacyGetArgsForCall)]
	fake.legacyGetArgsForCall = append(fake.legacyGetArgsForCall, struct {
	}{})
	stub := fake.LegacyGetStub
	fakeReturns := fake.legacyGetReturns
	fake.recordInvocation("LegacyGet", []interface{}{})
	fake.legacyGetMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAggregateGetter) LegacyGetCallCount() int {
	fake.legacyGetMutex.RLock()
	defer fake.legacyGetMutex.RUnlock()
	return len(fake.legacyGetArgsForCall)
}

func (fake *FakeAggregateGetter) LegacyGetCalls(stub func() []binding.LegacyBinding) {
	fake.legacyGetMutex.Lock()
	defer fake.legacyGetMutex.Unlock()
	fake.LegacyGetStub = stub
}

func (fake *FakeAggregateGetter) LegacyGetReturns(result1 []binding.LegacyBinding) {
	fake.legacyGetMutex.Lock()
	defer fake.legacyGetMutex.Unlock()
	fake.LegacyGetStub = nil
	fake.legacyGetReturns = struct {
		result1 []binding.LegacyBinding
	}{result1}
}

func (fake *FakeAggregateGetter) LegacyGetReturnsOnCall(i int, result1 []binding.LegacyBinding) {
	fake.legacyGetMutex.Lock()
	defer fake.legacyGetMutex.Unlock()
	fake.LegacyGetStub = nil
	if fake.legacyGetReturnsOnCall == nil {
		fake.legacyGetReturnsOnCall = make(map[int]struct {
			result1 []binding.LegacyBinding
		})
	}
	fake.legacyGetReturnsOnCall[i] = struct {
		result1 []binding.LegacyBinding
	}{result1}
}

func (fake *FakeAggregateGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.legacyGetMutex.RLock()
	defer fake.legacyGetMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAggregateGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cache.AggregateGetter = new(FakeAggregateGetter)
