// Code generated by counterfeiter. DO NOT EDIT.
package collectorfakes

import (
	"sync"

	"code.cloudfoundry.org/loggregator-agent-release/src/cmd/otel-collector-manager/app/collector"
)

type FakeGetter struct {
	GetAggregateMetricStub        func() (map[string]any, error)
	getAggregateMetricMutex       sync.RWMutex
	getAggregateMetricArgsForCall []struct {
	}
	getAggregateMetricReturns struct {
		result1 map[string]any
		result2 error
	}
	getAggregateMetricReturnsOnCall map[int]struct {
		result1 map[string]any
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGetter) GetAggregateMetric() (map[string]any, error) {
	fake.getAggregateMetricMutex.Lock()
	ret, specificReturn := fake.getAggregateMetricReturnsOnCall[len(fake.getAggregateMetricArgsForCall)]
	fake.getAggregateMetricArgsForCall = append(fake.getAggregateMetricArgsForCall, struct {
	}{})
	stub := fake.GetAggregateMetricStub
	fakeReturns := fake.getAggregateMetricReturns
	fake.recordInvocation("GetAggregateMetric", []interface{}{})
	fake.getAggregateMetricMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGetter) GetAggregateMetricCallCount() int {
	fake.getAggregateMetricMutex.RLock()
	defer fake.getAggregateMetricMutex.RUnlock()
	return len(fake.getAggregateMetricArgsForCall)
}

func (fake *FakeGetter) GetAggregateMetricCalls(stub func() (map[string]any, error)) {
	fake.getAggregateMetricMutex.Lock()
	defer fake.getAggregateMetricMutex.Unlock()
	fake.GetAggregateMetricStub = stub
}

func (fake *FakeGetter) GetAggregateMetricReturns(result1 map[string]any, result2 error) {
	fake.getAggregateMetricMutex.Lock()
	defer fake.getAggregateMetricMutex.Unlock()
	fake.GetAggregateMetricStub = nil
	fake.getAggregateMetricReturns = struct {
		result1 map[string]any
		result2 error
	}{result1, result2}
}

func (fake *FakeGetter) GetAggregateMetricReturnsOnCall(i int, result1 map[string]any, result2 error) {
	fake.getAggregateMetricMutex.Lock()
	defer fake.getAggregateMetricMutex.Unlock()
	fake.GetAggregateMetricStub = nil
	if fake.getAggregateMetricReturnsOnCall == nil {
		fake.getAggregateMetricReturnsOnCall = make(map[int]struct {
			result1 map[string]any
			result2 error
		})
	}
	fake.getAggregateMetricReturnsOnCall[i] = struct {
		result1 map[string]any
		result2 error
	}{result1, result2}
}

func (fake *FakeGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAggregateMetricMutex.RLock()
	defer fake.getAggregateMetricMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ collector.Getter = new(FakeGetter)
