#!/bin/sh

set -ex

readlink() {
  (
    cd $(dirname $1)
    echo $PWD/$(basename $1)
  )
}

# Place keys and certificates here
depot_path=$(readlink ./test-certs)
mkdir -p ${depot_path}

# Install certstrap
go get -v github.com/square/certstrap

# CA to distribute to loggregator certs
certstrap --depot-path ${depot_path} init --passphrase '' --common-name loggregatorCA --expires "25 years"
mv -f ${depot_path}/loggregatorCA.crt ${depot_path}/loggregator-ca.crt
mv -f ${depot_path}/loggregatorCA.key ${depot_path}/loggregator-ca.key
mv -f ${depot_path}/loggregatorCA.crl ${depot_path}/loggregator-ca.crl

# Agent certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name metron
certstrap --depot-path ${depot_path} sign metron --CA loggregator-ca --expires "25 years"

# Router certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name router
certstrap --depot-path ${depot_path} sign router --CA loggregator-ca --expires "25 years"

# Doppler certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name doppler
certstrap --depot-path ${depot_path} sign doppler --CA loggregator-ca --expires "25 years"

# Prom Scraper
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name prom-scraper
certstrap --depot-path ${depot_path} sign prom-scraper --CA loggregator-ca --expires "25 years"
