name: Go

on:
  push:
    branches:
    - main
    - v[0-9]*
  pull_request:
    branches:
    - main
    - v[0-9]*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - run: go run github.com/onsi/ginkgo/v2/ginkgo -r --race --randomize-all --randomize-suites --keep-going
        working-directory: src

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - run: go vet ./...
        working-directory: src

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "src/go.mod"
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          args: --config .golangci.yml --timeout 5m
          working-directory: src
