name: scripts

on:
  push:
    branches:
    - main
    - v[0-9]*
  pull_request:
    branches:
    - main
    - v[0-9]*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      - run: ./scripts/subtests/unit-test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true
      - run: ./scripts/subtests/lint
